const { UNKNOWN } = require('./common')

const SOURCE_LINKS = {
  project_context: 'https://github.com/kastigator/crusher-parts-backend/blob/main/PROJECT_CONTEXT.md',
  architecture_drive_folder: 'https://drive.google.com/drive/folders/1DKVc06GsgdBKWN2Fol0cz4Y75z8TQBOW',
  task_95: 'https://docs.google.com/document/d/1MLFfZavKFLpfeHWCHXS9YD3PCO7kNrMma1cSsgbDwPQ',
  task_96: 'https://docs.google.com/document/d/1U5dK6ITUdRZoLaDuMc0BDfMMOmimoDn6A4u4ibZHEc0',
}

function buildSystemState({ generatedAt, backend, frontend, database, deployment, featureDeployment }) {
  return {
    manifest_version: 2,
    generated_at: generatedAt,
    generated_by: {
      command: 'npm run ai-context:update',
      generator: 'scripts/ai-context/update.js',
      deterministic_format: true,
    },
    purpose: 'Reloadable, non-secret ERP state manifest for ChatGPT/Codex reviews',
    repositories: { backend, frontend },
    database,
    deployment: {
      ...deployment,
      active_backend_feature_status: featureDeployment,
      active_frontend_feature_status: UNKNOWN,
    },
    protected_data: ['Classifier', 'Engineering'],
    source_links: SOURCE_LINKS,
  }
}

function renderSystemState(state) {
  return `${JSON.stringify(state, null, 2)}\n`
}

function display(value) {
  if (value === null || value === undefined || value === '') return UNKNOWN
  if (Array.isArray(value)) return value.length ? value.join(', ') : 'none'
  if (typeof value === 'boolean') return value ? 'Yes' : 'No'
  return String(value)
}

function renderDatabaseState(database, generatedAt) {
  const available = database.availability === 'AVAILABLE'
  const inventory = database.inventory || {}
  const ledger = database.migration_ledger || {}
  const tables = available ? inventory.table_names || [] : []
  const views = available ? inventory.view_names || [] : []
  return `# Database State

Generated: ${generatedAt}

Generated by \`npm run ai-context:update\`. This file contains metadata/schema information only. It contains no application rows, credentials, secrets, Classifier records or Engineering records.

## Source status

| Property | Value |
|---|---|
| Availability | \`${display(database.availability)}\` |
| Reason when unavailable | ${display(database.reason)} |
| Platform | ${display(database.platform)} |
| Instance | \`${display(database.instance)}\` |
| Database | \`${display(database.database)}\` |
| Engine | \`${display(database.engine_version)}\` |
| Current schema fingerprint | \`${display(database.schema_fingerprint)}\` |
| Expected schema fingerprint | \`${display(database.expected_schema_fingerprint)}\` |
| Schema drift | ${display(database.schema_drift)} |
| Pending managed migrations | ${display(database.pending_migrations)} |
| Latest applied migration | \`${display(database.latest_applied_migration)}\` |

## Inventory summary

| Object | Count |
|---|---:|
| Base tables | ${display(inventory.base_tables)} |
| Views | ${display(inventory.views)} |
| Columns | ${display(inventory.columns)} |

## Migration ledger

| Status class | Count |
|---|---:|
| Rows | ${display(ledger.rows)} |
| Baseline | ${display(ledger.baseline)} |
| Applied | ${display(ledger.applied)} |
| Historical FAILED with acknowledged forward fix | ${display(ledger.historical_failed_with_acknowledged_forward_fix)} |
| Unresolved FAILED | ${display(ledger.unresolved_failed)} |
| Running | ${display(ledger.running)} |

Historical FAILED rows with acknowledged forward fixes are retained audit evidence and are not silently reclassified as APPLIED.

## Base-table inventory

\`\`\`text
${tables.length ? tables.join('\n') : UNKNOWN}
\`\`\`

## View inventory

\`\`\`text
${views.length ? views.join('\n') : UNKNOWN}
\`\`\`

## Safety and interpretation

- \`AVAILABLE\` means this run read live metadata successfully.
- \`UNKNOWN\` means the value could not be proven in this run; it must not be replaced with a remembered value.
- The live fingerprint and migration ledger are authoritative when available.
- Managed SQL under \`migrations/managed\` is the forward migration source. Historical \`/sql\` files remain pre-baseline evidence.
- Exact live DDL, when required, must use a new schema-only export. Routine context generation never exports business rows.
`
}

module.exports = {
  SOURCE_LINKS,
  buildSystemState,
  renderDatabaseState,
  renderSystemState,
}
