const db=require('../../utils/db')
const warehouse=require('../warehouseInventory/commandService')
const {DispatchDeliveryError}=require('./domainError')
const {actor,event,id,json,key,parseJson,qty,sha256,text,toId}=require('./helpers')
const EPS=0.0005
const tx=async(fn)=>{const conn=await db.getConnection();try{await conn.beginTransaction();const out=await fn(conn);await conn.commit();return out}catch(error){await conn.rollback();throw error}finally{conn.release()}}
const version=(payload)=>{const n=Number(payload.row_version);if(!Number.isSafeInteger(n)||n<1)throw new DispatchDeliveryError('ROW_VERSION_REQUIRED','Требуется row_version');return n}
const snapshotAvailable=(value)=>value&&typeof value==='object'&&(value.available===true||Object.keys(value).some(k=>!['available','reason'].includes(k)&&value[k]!=null&&String(value[k]).trim()))

async function createOrder(payload,userId){
  const requestKey=key(payload.idempotency_key),items=Array.isArray(payload.allocations)?payload.allocations:[]
  if(!items.length)throw new DispatchDeliveryError('ALLOCATIONS_REQUIRED','Нужна хотя бы одна Contract Commitment allocation')
  return tx(async conn=>{
    const [[duplicate]]=await conn.execute('SELECT id,status FROM dispatch_orders WHERE idempotency_key=? FOR UPDATE',[requestKey]);if(duplicate)return{order_id:duplicate.id,status:duplicate.status,already_exists:true}
    const commitmentIds=[...new Set(items.map(x=>id(x.contract_commitment_id,'contract_commitment_id')))]
    const marks=commitmentIds.map(()=>'?').join(',')
    const [rows]=await conn.execute(`SELECT c.*,cc.client_id,cc.contract_number,r.status revision_status,r.shipping_address_snapshot_json,r.client_contact_snapshot_json,r.company_legal_snapshot_json,r.client_snapshot_json
      FROM contract_commitments c JOIN contract_cases cc ON cc.id=c.contract_case_id JOIN contract_revisions r ON r.id=c.effective_contract_revision_id
      WHERE c.id IN (${marks}) FOR UPDATE`,commitmentIds)
    if(rows.length!==commitmentIds.length)throw new DispatchDeliveryError('COMMITMENT_NOT_FOUND','Contract Commitment не найден',404)
    const first=rows[0]
    if(rows.some(r=>r.revision_status!=='EFFECTIVE'||r.commitment_type!=='SUPPLY'))throw new DispatchDeliveryError('EFFECTIVE_SUPPLY_COMMITMENT_REQUIRED','Dispatch принимает только effective SUPPLY commitments',409)
    if(rows.some(r=>Number(r.contract_case_id)!==Number(first.contract_case_id)||Number(r.client_id)!==Number(first.client_id)||Number(r.effective_contract_revision_id)!==Number(first.effective_contract_revision_id)))throw new DispatchDeliveryError('CONTRACT_SCOPE_MISMATCH','Один Dispatch Order должен иметь общий Contract Revision и client',409)
    const destination=parseJson(first.shipping_address_snapshot_json,{}),contact=parseJson(first.client_contact_snapshot_json,{}),company=parseJson(first.company_legal_snapshot_json,{})
    if(!snapshotAvailable(destination))throw new DispatchDeliveryError('DESTINATION_SNAPSHOT_REQUIRED','В Contract Revision отсутствует immutable shipping destination snapshot',409)
    if(rows.some(r=>sha256(parseJson(r.shipping_address_snapshot_json,{}))!==sha256(destination)))throw new DispatchDeliveryError('DESTINATION_MISMATCH','Commitments имеют несовместимые destination snapshots',409)
    const destinationHash=sha256({destination,contact}),trace={contract_case_id:first.contract_case_id,contract_revision_id:first.effective_contract_revision_id,contract_number:first.contract_number,commitment_ids:commitmentIds,source:'contract_commitments'}
    const [insert]=await conn.execute(`INSERT INTO dispatch_orders(order_number,client_id,source_contract_case_id,source_contract_revision_id,destination_snapshot_json,contact_snapshot_json,company_legal_snapshot_json,source_trace_snapshot_json,destination_hash,status,planned_release_at,notes,idempotency_key,created_by_user_id)
      VALUES(?,?,?,?,?,?,?,?,?,'PLANNING',?,?,?,?)`,[`DO-${Date.now()}`,first.client_id,first.contract_case_id,first.effective_contract_revision_id,json(destination),json(contact),json(company),json(trace),destinationHash,payload.planned_release_at?new Date(payload.planned_release_at):null,payload.notes||null,requestKey,actor(userId)])
    const plannedByCatalog=new Map()
    for(const item of items){const source=rows.find(r=>Number(r.id)===Number(item.contract_commitment_id)),allocated=qty(item.quantity,'allocated quantity')
      const [[sum]]=await conn.execute(`SELECT COALESCE(SUM(a.allocated_quantity),0) total FROM dispatch_order_allocations a JOIN dispatch_orders o ON o.id=a.dispatch_order_id WHERE a.contract_commitment_id=? AND o.status<>'CANCELLED'`,[source.id])
      if(Number(sum.total)+allocated>Number(source.quantity)+EPS)throw new DispatchDeliveryError('COMMITMENT_OVER_ALLOCATION','Dispatch allocations превышают contractual required quantity',409,{commitment_id:source.id})
      const subject=parseJson(source.subject_snapshot_json,{}),catalogId=toId(subject.catalog_position_id||subject.catalogPositionId)
      if(!catalogId)throw new DispatchDeliveryError('CATALOG_POSITION_REQUIRED','Contract Commitment не содержит canonical Catalog Position',409,{commitment_id:source.id})
      const [[stock]]=await conn.execute(`SELECT COALESCE(SUM(CASE WHEN u.quality_status='RELEASED' AND u.status='ACTIVE' THEN state.physical_quantity-state.reserved_quantity ELSE 0 END),0) available_quantity FROM warehouse_stock_units u JOIN (SELECT stock_unit_id,SUM(quantity_delta) physical_quantity,SUM(reserved_delta) reserved_quantity FROM warehouse_inventory_movements GROUP BY stock_unit_id) state ON state.stock_unit_id=u.id WHERE u.catalog_position_id=?`,[catalogId])
      const planned=Number(plannedByCatalog.get(catalogId)||0)+allocated;plannedByCatalog.set(catalogId,planned)
      if(Number(stock.available_quantity)+EPS<planned)throw new DispatchDeliveryError('WAREHOUSE_STOCK_NOT_AVAILABLE','Недостаточно RELEASED available Warehouse stock для Dispatch Order',409,{commitment_id:source.id,catalog_position_id:catalogId,available_quantity:Number(stock.available_quantity),requested_quantity:planned})
      const snap={commitment_id:source.id,commitment_hash:source.commitment_hash,contract_line_id:source.contract_line_id,subject,delivery:parseJson(source.delivery_snapshot_json,{}),upstream_trace:parseJson(source.upstream_trace_snapshot_json,{})}
      await conn.execute(`INSERT INTO dispatch_order_allocations(dispatch_order_id,contract_commitment_id,catalog_position_id,required_quantity_snapshot,allocated_quantity,uom,commitment_snapshot_json,commitment_hash) VALUES(?,?,?,?,?,?,?,?)`,[insert.insertId,source.id,catalogId,source.quantity,allocated,source.uom,json(snap),source.commitment_hash])}
    await event(conn,'DispatchOrderCreated','dispatch_order',insert.insertId,userId,{commitment_ids:commitmentIds,destination_hash:destinationHash},{domain:'contracts',entity_type:'contract_case',entity_id:first.contract_case_id})
    return{order_id:insert.insertId,status:'PLANNING'}
  })
}

async function requestPicking(orderIdInput,payload,userId){const orderId=id(orderIdInput,'order_id'),warehouseId=id(payload.warehouse_id,'warehouse_id'),requestKey=key(payload.idempotency_key),lines=Array.isArray(payload.lines)?payload.lines:[];if(!lines.length)throw new DispatchDeliveryError('PICKING_LINES_REQUIRED','Нужны Warehouse reservation allocations')
  return tx(async conn=>{const [[duplicate]]=await conn.execute('SELECT id,status FROM dispatch_picking_requests WHERE idempotency_key=? FOR UPDATE',[requestKey]);if(duplicate)return{picking_request_id:duplicate.id,status:duplicate.status,already_exists:true}
    const [[order]]=await conn.execute('SELECT * FROM dispatch_orders WHERE id=? FOR UPDATE',[orderId]);if(!order)throw new DispatchDeliveryError('ORDER_NOT_FOUND','Dispatch Order не найден',404);if(!['PLANNING','WAITING_CONSOLIDATION','READY_FOR_PICKING','PICKING'].includes(order.status))throw new DispatchDeliveryError('ORDER_PICKING_STATE_INVALID','Order недоступен для picking',409)
    const [header]=await conn.execute(`INSERT INTO dispatch_picking_requests(request_number,dispatch_order_id,warehouse_id,status,idempotency_key,requested_by_user_id) VALUES(?,?,?,'ALLOCATED',?,?)`,[`PICK-${Date.now()}-${orderId}`,orderId,warehouseId,requestKey,actor(userId)])
    for(const item of lines){const allocationId=id(item.dispatch_order_allocation_id,'dispatch_order_allocation_id'),reservationAllocationId=id(item.warehouse_reservation_allocation_id,'warehouse_reservation_allocation_id'),requested=qty(item.quantity)
      const [[source]]=await conn.execute(`SELECT a.id allocation_id,a.dispatch_order_id,a.allocated_quantity,a.uom,wa.stock_unit_id,wa.quantity reserved_quantity,wa.status allocation_status,wr.status reservation_status,wr.source_domain,wr.source_entity_type,wr.source_entity_id,su.warehouse_id,su.quality_status
       FROM dispatch_order_allocations a JOIN warehouse_inventory_reservation_allocations wa ON wa.id=? JOIN warehouse_inventory_reservations wr ON wr.id=wa.warehouse_inventory_reservation_id JOIN warehouse_stock_units su ON su.id=wa.stock_unit_id WHERE a.id=? FOR UPDATE`,[reservationAllocationId,allocationId])
      if(!source||Number(source.dispatch_order_id)!==orderId)throw new DispatchDeliveryError('ORDER_ALLOCATION_MISMATCH','Allocation не принадлежит Dispatch Order',409)
      if(source.source_domain!=='dispatch_delivery'||Number(source.source_entity_id)!==orderId||source.allocation_status!=='ACTIVE'||source.reservation_status!=='ACTIVE')throw new DispatchDeliveryError('ACTIVE_DISPATCH_RESERVATION_REQUIRED','Warehouse reservation должна быть активной и принадлежать Dispatch Order',409)
      if(Number(source.warehouse_id)!==warehouseId||source.quality_status!=='RELEASED'||Math.abs(Number(source.reserved_quantity)-requested)>EPS)throw new DispatchDeliveryError('WAREHOUSE_RESERVATION_MISMATCH','Warehouse, quality или quantity reservation не совпадает',409)
      const [[used]]=await conn.execute(`SELECT COALESCE(SUM(requested_quantity),0) total FROM dispatch_picking_request_lines WHERE dispatch_order_allocation_id=? AND status<>'CANCELLED'`,[allocationId]);if(Number(used.total)+requested>Number(source.allocated_quantity)+EPS)throw new DispatchDeliveryError('PICKING_OVER_ALLOCATION','Picking превышает Dispatch allocation',409)
      await conn.execute(`INSERT INTO dispatch_picking_request_lines(dispatch_picking_request_id,dispatch_order_allocation_id,warehouse_reservation_allocation_id,stock_unit_id,requested_quantity,uom,status,lineage_snapshot_json) VALUES(?,?,?,?,?,?,'ALLOCATED',?)`,[header.insertId,allocationId,reservationAllocationId,source.stock_unit_id,requested,source.uom,json({reservation_allocation_id:reservationAllocationId,stock_unit_id:source.stock_unit_id,dispatch_order_id:orderId})])}
    await conn.execute("UPDATE dispatch_orders SET status='PICKING',row_version=row_version+1 WHERE id=?",[orderId]);await event(conn,'PickingRequested','dispatch_picking_request',header.insertId,userId,{order_id:orderId,warehouse_id:warehouseId,line_count:lines.length},{domain:'warehouse_inventory',entity_type:'warehouse_inventory_reservation',entity_id:null});return{picking_request_id:header.insertId,status:'ALLOCATED'}})}

async function confirmPicking(requestIdInput,payload,userId){const requestId=id(requestIdInput,'picking_request_id'),v=version(payload),evidence=text(payload.evidence_reference,'evidence_reference');return tx(async conn=>{const [[request]]=await conn.execute('SELECT * FROM dispatch_picking_requests WHERE id=? FOR UPDATE',[requestId]);if(!request)throw new DispatchDeliveryError('PICKING_NOT_FOUND','Picking Request не найден',404);if(request.status==='PICKED'||request.status==='STAGED')return{picking_request_id:requestId,status:request.status,already_exists:true};if(Number(request.row_version)!==v)throw new DispatchDeliveryError('VERSION_CONFLICT','Picking Request изменён',409);const [lines]=await conn.execute('SELECT * FROM dispatch_picking_request_lines WHERE dispatch_picking_request_id=? FOR UPDATE',[requestId]);if(!lines.length)throw new DispatchDeliveryError('PICKING_LINES_REQUIRED','Picking Request пуст',409);await conn.execute("UPDATE dispatch_picking_request_lines SET picked_quantity=requested_quantity,status='PICKED' WHERE dispatch_picking_request_id=?",[requestId]);await conn.execute("UPDATE dispatch_picking_requests SET status='PICKED',evidence_reference=?,confirmed_by_user_id=?,confirmed_at=NOW(6),row_version=row_version+1 WHERE id=?",[evidence,actor(userId),requestId]);await conn.execute("UPDATE dispatch_orders SET status='PACKING',row_version=row_version+1 WHERE id=?",[request.dispatch_order_id]);await event(conn,'PickingConfirmed','dispatch_picking_request',requestId,userId,{evidence_reference:evidence,stock_unit_ids:lines.map(x=>x.stock_unit_id)},{domain:'warehouse_inventory',entity_type:'warehouse_picking_evidence',entity_id:null});return{picking_request_id:requestId,status:'PICKED'}})}

async function createPackage(payload,userId){const orderId=id(payload.dispatch_order_id,'dispatch_order_id'),requestKey=key(payload.idempotency_key),contents=Array.isArray(payload.contents)?payload.contents:[];if(!contents.length)throw new DispatchDeliveryError('PACKAGE_CONTENTS_REQUIRED','Package должен содержать picked Stock Units')
  return tx(async conn=>{const [[duplicate]]=await conn.execute('SELECT id,status FROM dispatch_packages WHERE idempotency_key=? FOR UPDATE',[requestKey]);if(duplicate)return{package_id:duplicate.id,status:duplicate.status,already_exists:true};const [[order]]=await conn.execute('SELECT id,status FROM dispatch_orders WHERE id=? FOR UPDATE',[orderId]);if(!order)throw new DispatchDeliveryError('ORDER_NOT_FOUND','Dispatch Order не найден',404);const [header]=await conn.execute(`INSERT INTO dispatch_packages(package_number,dispatch_order_id,package_type,weight_kg,dimensions_snapshot_json,seals_snapshot_json,idempotency_key,created_by_user_id) VALUES(?,?,?,?,?,?,?,?)`,[`PKG-${Date.now()}-${orderId}`,orderId,payload.package_type||null,payload.weight_kg==null?null:Number(payload.weight_kg),json(payload.dimensions),json(payload.seals),requestKey,actor(userId)])
    for(const item of contents){const lineId=id(item.picking_request_line_id,'picking_request_line_id'),amount=qty(item.quantity);const [[line]]=await conn.execute(`SELECT l.*,r.dispatch_order_id,wa.quantity reserved_quantity,wa.status reservation_status FROM dispatch_picking_request_lines l JOIN dispatch_picking_requests r ON r.id=l.dispatch_picking_request_id JOIN warehouse_inventory_reservation_allocations wa ON wa.id=l.warehouse_reservation_allocation_id WHERE l.id=? FOR UPDATE`,[lineId]);if(!line||Number(line.dispatch_order_id)!==orderId||line.status!=='PICKED')throw new DispatchDeliveryError('PICKED_LINE_REQUIRED','Package content должен ссылаться на picked line этого Order',409);if(Math.abs(Number(line.picked_quantity)-amount)>EPS||Math.abs(Number(line.reserved_quantity)-amount)>EPS||line.reservation_status!=='ACTIVE')throw new DispatchDeliveryError('EXACT_PACKAGE_LINEAGE_REQUIRED','Package quantity должна точно совпадать с picked/reserved Stock Unit quantity',409);const lineage={picking_request_line_id:line.id,reservation_allocation_id:line.warehouse_reservation_allocation_id,stock_unit_id:line.stock_unit_id,allocation_id:line.dispatch_order_allocation_id,quantity:amount};await conn.execute(`INSERT INTO dispatch_package_contents(dispatch_package_id,dispatch_order_allocation_id,dispatch_picking_request_line_id,warehouse_reservation_allocation_id,stock_unit_id,quantity,uom,lineage_snapshot_json,lineage_hash) VALUES(?,?,?,?,?,?,?,?,?)`,[header.insertId,line.dispatch_order_allocation_id,line.id,line.warehouse_reservation_allocation_id,line.stock_unit_id,amount,line.uom,json(lineage),sha256(lineage)])}
    await event(conn,'PackageCreated','dispatch_package',header.insertId,userId,{order_id:orderId,content_count:contents.length});return{package_id:header.insertId,status:'OPEN'}})}

async function packPackage(packageIdInput,payload,userId){const packageId=id(packageIdInput,'package_id'),v=version(payload);return tx(async conn=>{const [[row]]=await conn.execute('SELECT * FROM dispatch_packages WHERE id=? FOR UPDATE',[packageId]);if(!row)throw new DispatchDeliveryError('PACKAGE_NOT_FOUND','Package не найден',404);if(row.status==='PACKED')return{package_id:packageId,status:'PACKED',already_exists:true};if(row.status!=='OPEN'||Number(row.row_version)!==v)throw new DispatchDeliveryError('PACKAGE_STATE_CONFLICT','Package state/version conflict',409);const [[count]]=await conn.execute('SELECT COUNT(*) count FROM dispatch_package_contents WHERE dispatch_package_id=?',[packageId]);if(!Number(count.count))throw new DispatchDeliveryError('PACKAGE_CONTENTS_REQUIRED','Пустой package нельзя упаковать',409);await conn.execute("UPDATE dispatch_packages SET status='PACKED',packed_at=NOW(6),row_version=row_version+1 WHERE id=?",[packageId]);await event(conn,'PackagePacked','dispatch_package',packageId,userId,{content_count:Number(count.count)});return{package_id:packageId,status:'PACKED'}})}

async function createShipment(payload,userId){const requestKey=key(payload.idempotency_key),packageIds=[...new Set((payload.package_ids||[]).map(x=>id(x,'package_id')))];if(!packageIds.length)throw new DispatchDeliveryError('PACKAGES_REQUIRED','Shipment должен содержать packages')
 return tx(async conn=>{const [[duplicate]]=await conn.execute('SELECT id,status FROM dispatch_shipments WHERE idempotency_key=? FOR UPDATE',[requestKey]);if(duplicate)return{shipment_id:duplicate.id,status:duplicate.status,already_exists:true};const [rows]=await conn.execute(`SELECT p.*,o.destination_snapshot_json,o.contact_snapshot_json,o.company_legal_snapshot_json,o.destination_hash,o.status order_status FROM dispatch_packages p JOIN dispatch_orders o ON o.id=p.dispatch_order_id WHERE p.id IN (${packageIds.map(()=>'?').join(',')}) FOR UPDATE`,packageIds);if(rows.length!==packageIds.length||rows.some(x=>x.status!=='PACKED'))throw new DispatchDeliveryError('PACKED_PACKAGES_REQUIRED','Все packages должны быть PACKED',409);const first=rows[0];if(rows.some(x=>x.destination_hash!==first.destination_hash))throw new DispatchDeliveryError('CONSOLIDATION_DESTINATION_MISMATCH','Consolidation разрешена только для совместимого destination snapshot',409);const carrier=payload.carrier||{},tracking=payload.tracking||{},terms=payload.terms||{};if(!snapshotAvailable(carrier))throw new DispatchDeliveryError('CARRIER_SNAPSHOT_REQUIRED','Требуется carrier snapshot',409);const snap={destination:parseJson(first.destination_snapshot_json,{}),contact:parseJson(first.contact_snapshot_json,{}),company:parseJson(first.company_legal_snapshot_json,{}),carrier,tracking,terms,package_ids:packageIds}
  const [header]=await conn.execute(`INSERT INTO dispatch_shipments(shipment_number,status,destination_snapshot_json,contact_snapshot_json,company_legal_snapshot_json,carrier_snapshot_json,tracking_snapshot_json,terms_snapshot_json,destination_hash,idempotency_key,created_by_user_id) VALUES(?,'READY',?,?,?,?,?,?,?,?,?)`,[`SHP-${Date.now()}`,json(snap.destination),json(snap.contact),json(snap.company),json(carrier),json(tracking),json(terms),first.destination_hash,requestKey,actor(userId)]);await conn.execute('INSERT INTO dispatch_shipment_revisions(dispatch_shipment_id,revision_number,snapshot_json,content_hash,reason,created_by_user_id) VALUES(?,1,?,?,?,?)',[header.insertId,json(snap),sha256(snap),payload.reason||'Initial shipment plan',actor(userId)]);for(const packageId of packageIds)await conn.execute('INSERT INTO dispatch_shipment_packages(dispatch_shipment_id,dispatch_package_id) VALUES(?,?)',[header.insertId,packageId]);await conn.execute("UPDATE dispatch_packages SET status='ASSIGNED',row_version=row_version+1 WHERE id IN ("+packageIds.map(()=>'?').join(',')+")",packageIds);await conn.execute("UPDATE dispatch_orders SET status='READY_TO_SHIP',row_version=row_version+1 WHERE id IN ("+[...new Set(rows.map(x=>x.dispatch_order_id))].map(()=>'?').join(',')+")",[...new Set(rows.map(x=>x.dispatch_order_id))]);await event(conn,'ShipmentCreated','dispatch_shipment',header.insertId,userId,{package_ids:packageIds,destination_hash:first.destination_hash});return{shipment_id:header.insertId,status:'READY'}})}

async function reviseShipment(shipmentIdInput,payload,userId){const shipmentId=id(shipmentIdInput,'shipment_id'),v=version(payload);return tx(async conn=>{const [[shipment]]=await conn.execute('SELECT * FROM dispatch_shipments WHERE id=? FOR UPDATE',[shipmentId]);if(!shipment)throw new DispatchDeliveryError('SHIPMENT_NOT_FOUND','Shipment не найден',404);if(!['DRAFT','READY'].includes(shipment.status))throw new DispatchDeliveryError('DISPATCHED_SHIPMENT_IMMUTABLE','После dispatch shipment facts неизменяемы; используйте evidence/correction flow',409);if(Number(shipment.row_version)!==v)throw new DispatchDeliveryError('VERSION_CONFLICT','Shipment изменён',409);const [packages]=await conn.execute('SELECT dispatch_package_id FROM dispatch_shipment_packages WHERE dispatch_shipment_id=? ORDER BY dispatch_package_id',[shipmentId]);const carrier=payload.carrier||parseJson(shipment.carrier_snapshot_json,{}),tracking=payload.tracking||parseJson(shipment.tracking_snapshot_json,{}),terms=payload.terms||parseJson(shipment.terms_snapshot_json,{}),snap={destination:parseJson(shipment.destination_snapshot_json,{}),contact:parseJson(shipment.contact_snapshot_json,{}),company:parseJson(shipment.company_legal_snapshot_json,{}),carrier,tracking,terms,package_ids:packages.map(x=>x.dispatch_package_id)},next=Number(shipment.current_revision_number)+1;await conn.execute('INSERT INTO dispatch_shipment_revisions(dispatch_shipment_id,revision_number,snapshot_json,content_hash,reason,created_by_user_id) VALUES(?,?,?,?,?,?)',[shipmentId,next,json(snap),sha256(snap),text(payload.reason,'reason',1000),actor(userId)]);await conn.execute('UPDATE dispatch_shipments SET carrier_snapshot_json=?,tracking_snapshot_json=?,terms_snapshot_json=?,current_revision_number=?,row_version=row_version+1 WHERE id=?',[json(carrier),json(tracking),json(terms),next,shipmentId]);await event(conn,'ShipmentRevised','dispatch_shipment',shipmentId,userId,{revision_number:next,content_hash:sha256(snap)});return{shipment_id:shipmentId,revision_number:next,status:shipment.status}})}

async function dispatchShipment(shipmentIdInput,payload,userId){const shipmentId=id(shipmentIdInput,'shipment_id'),v=version(payload),requestKey=key(payload.idempotency_key);return tx(async conn=>{const [[shipment]]=await conn.execute('SELECT * FROM dispatch_shipments WHERE id=? FOR UPDATE',[shipmentId]);if(!shipment)throw new DispatchDeliveryError('SHIPMENT_NOT_FOUND','Shipment не найден',404);if(shipment.status==='DISPATCHED'||shipment.status==='IN_TRANSIT'||shipment.status==='PARTIALLY_DELIVERED'||shipment.status==='DELIVERED')return{shipment_id:shipmentId,status:shipment.status,already_exists:true};if(shipment.status!=='READY'||Number(shipment.row_version)!==v)throw new DispatchDeliveryError('SHIPMENT_STATE_CONFLICT','Shipment state/version conflict',409);const [lines]=await conn.execute(`SELECT c.id package_content_id,c.warehouse_reservation_allocation_id,c.stock_unit_id,c.quantity,c.dispatch_order_allocation_id,p.id package_id,p.dispatch_order_id FROM dispatch_shipment_packages sp JOIN dispatch_packages p ON p.id=sp.dispatch_package_id JOIN dispatch_package_contents c ON c.dispatch_package_id=p.id WHERE sp.dispatch_shipment_id=? FOR UPDATE`,[shipmentId]);if(!lines.length)throw new DispatchDeliveryError('SHIPMENT_CONTENT_REQUIRED','Shipment не содержит Stock Unit lineage',409);const issueHash=sha256(lines.map(x=>({content_id:x.package_content_id,reservation_allocation_id:x.warehouse_reservation_allocation_id,stock_unit_id:x.stock_unit_id,quantity:Number(x.quantity)})).sort((a,b)=>a.content_id-b.content_id));const issued=await warehouse.issueForShipment(conn,{shipment_id:shipmentId,lines,evidence:{idempotency_key:requestKey,carrier:parseJson(shipment.carrier_snapshot_json,{}),tracking:parseJson(shipment.tracking_snapshot_json,{})}},userId);await conn.execute("UPDATE dispatch_shipments SET status='DISPATCHED',warehouse_issue_hash=?,dispatched_at=NOW(6),row_version=row_version+1 WHERE id=?",[issueHash,shipmentId]);await conn.execute("UPDATE dispatch_packages p JOIN dispatch_shipment_packages sp ON sp.dispatch_package_id=p.id SET p.status='DISPATCHED',p.row_version=p.row_version+1 WHERE sp.dispatch_shipment_id=?",[shipmentId]);const orderIds=[...new Set(lines.map(x=>x.dispatch_order_id))];for(const orderId of orderIds){const [[counts]]=await conn.execute(`SELECT COUNT(DISTINCT p.id) total,SUM(CASE WHEN p.status='DISPATCHED' THEN 1 ELSE 0 END) sent FROM dispatch_packages p WHERE p.dispatch_order_id=?`,[orderId]);await conn.execute('UPDATE dispatch_orders SET status=?,row_version=row_version+1 WHERE id=?',[Number(counts.sent)>=Number(counts.total)?'DISPATCHED':'PARTIALLY_DISPATCHED',orderId])}await event(conn,'ShipmentDispatched','dispatch_shipment',shipmentId,userId,{warehouse_issue_hash:issueHash,movement_ids:issued.map(x=>x.movement_id),idempotency_key:requestKey},{domain:'warehouse_inventory',entity_type:'warehouse_shipment_issue',entity_id:shipmentId});return{shipment_id:shipmentId,status:'DISPATCHED',warehouse_issue_hash:issueHash,issued}})}

async function confirmDelivery(shipmentIdInput,payload,userId){const shipmentId=id(shipmentIdInput,'shipment_id'),requestKey=key(payload.idempotency_key),lines=Array.isArray(payload.lines)?payload.lines:[];if(!lines.length)throw new DispatchDeliveryError('DELIVERY_LINES_REQUIRED','POD должен содержать delivered quantity mapping')
 return tx(async conn=>{const [[duplicate]]=await conn.execute('SELECT id FROM dispatch_delivery_confirmations WHERE idempotency_key=? FOR UPDATE',[requestKey]);if(duplicate)return{delivery_confirmation_id:duplicate.id,already_exists:true};const [[shipment]]=await conn.execute("SELECT * FROM dispatch_shipments WHERE id=? FOR UPDATE",[shipmentId]);if(!shipment)throw new DispatchDeliveryError('SHIPMENT_NOT_FOUND','Shipment не найден',404);if(!['DISPATCHED','IN_TRANSIT','PARTIALLY_DELIVERED'].includes(shipment.status))throw new DispatchDeliveryError('DISPATCH_REQUIRED','Delivery Confirmation разрешён только после ShipmentDispatched',409);const deliveredAt=new Date(payload.delivered_at);if(Number.isNaN(deliveredAt.getTime()))throw new DispatchDeliveryError('INVALID_DATE','Некорректный delivered_at');const receivedBy=text(payload.received_by,'received_by',255),evidence=text(payload.evidence_reference,'evidence_reference'),evidenceSnapshot=payload.evidence||{};const [header]=await conn.execute(`INSERT INTO dispatch_delivery_confirmations(confirmation_number,dispatch_shipment_id,delivered_at,received_by,evidence_reference,evidence_snapshot_json,evidence_hash,idempotency_key,confirmed_by_user_id) VALUES(?,?,?,?,?,?,?,?,?)`,[`POD-${Date.now()}-${shipmentId}`,shipmentId,deliveredAt,receivedBy,evidence,json(evidenceSnapshot),sha256({shipmentId,deliveredAt:deliveredAt.toISOString(),receivedBy,evidence,evidenceSnapshot,lines}),requestKey,actor(userId)])
  const touchedOrders=new Set();for(const item of lines){const allocationId=id(item.dispatch_order_allocation_id,'dispatch_order_allocation_id'),amount=qty(item.delivered_quantity,'delivered_quantity');const [[state]]=await conn.execute(`SELECT a.*,p.dispatch_order_id,COALESCE((SELECT SUM(pc.quantity) FROM dispatch_shipment_packages sp JOIN dispatch_packages px ON px.id=sp.dispatch_package_id JOIN dispatch_package_contents pc ON pc.dispatch_package_id=px.id WHERE sp.dispatch_shipment_id=? AND pc.dispatch_order_allocation_id=a.id),0) shipment_dispatched,COALESCE((SELECT SUM(dl.delivered_quantity) FROM dispatch_delivery_confirmation_lines dl JOIN dispatch_delivery_confirmations dc ON dc.id=dl.dispatch_delivery_confirmation_id WHERE dc.dispatch_shipment_id=? AND dc.status='CONFIRMED' AND dl.dispatch_order_allocation_id=a.id),0) already_delivered FROM dispatch_order_allocations a JOIN dispatch_packages p ON p.dispatch_order_id=a.dispatch_order_id JOIN dispatch_shipment_packages sp0 ON sp0.dispatch_package_id=p.id WHERE a.id=? AND sp0.dispatch_shipment_id=? LIMIT 1 FOR UPDATE`,[shipmentId,shipmentId,allocationId,shipmentId]);if(!state)throw new DispatchDeliveryError('SHIPMENT_ALLOCATION_MISMATCH','Allocation не входит в Shipment',409);if(Number(state.already_delivered)+amount>Number(state.shipment_dispatched)+EPS)throw new DispatchDeliveryError('DELIVERY_EXCEEDS_DISPATCHED','Delivered quantity превышает dispatched quantity',409);await conn.execute('INSERT INTO dispatch_delivery_confirmation_lines(dispatch_delivery_confirmation_id,dispatch_order_allocation_id,delivered_quantity,uom) VALUES(?,?,?,?,?)'.replace('?,?,?,?,?','?,?,?,?'),[header.insertId,allocationId,amount,state.uom]);touchedOrders.add(Number(state.dispatch_order_id))}
  const [[shipmentTotals]]=await conn.execute(`SELECT COALESCE(SUM(c.quantity),0) dispatched,COALESCE((SELECT SUM(dl.delivered_quantity) FROM dispatch_delivery_confirmation_lines dl JOIN dispatch_delivery_confirmations dc ON dc.id=dl.dispatch_delivery_confirmation_id WHERE dc.dispatch_shipment_id=? AND dc.status='CONFIRMED'),0) delivered FROM dispatch_shipment_packages sp JOIN dispatch_package_contents c ON c.dispatch_package_id=sp.dispatch_package_id WHERE sp.dispatch_shipment_id=?`,[shipmentId,shipmentId]);const shipmentStatus=Number(shipmentTotals.delivered)+EPS>=Number(shipmentTotals.dispatched)?'DELIVERED':'PARTIALLY_DELIVERED';await conn.execute('UPDATE dispatch_shipments SET status=?,row_version=row_version+1 WHERE id=?',[shipmentStatus,shipmentId]);if(shipmentStatus==='DELIVERED')await conn.execute("UPDATE dispatch_packages p JOIN dispatch_shipment_packages sp ON sp.dispatch_package_id=p.id SET p.status='DELIVERED',p.row_version=p.row_version+1 WHERE sp.dispatch_shipment_id=?",[shipmentId]);for(const orderId of touchedOrders){const [[s]]=await conn.execute(`SELECT COALESCE(SUM(a.allocated_quantity),0) allocated,COALESCE((SELECT SUM(dl.delivered_quantity) FROM dispatch_delivery_confirmation_lines dl JOIN dispatch_order_allocations aa ON aa.id=dl.dispatch_order_allocation_id JOIN dispatch_delivery_confirmations dc ON dc.id=dl.dispatch_delivery_confirmation_id WHERE aa.dispatch_order_id=? AND dc.status='CONFIRMED'),0) delivered FROM dispatch_order_allocations a WHERE a.dispatch_order_id=?`,[orderId,orderId]);await conn.execute('UPDATE dispatch_orders SET status=?,row_version=row_version+1 WHERE id=?',[Number(s.delivered)+EPS>=Number(s.allocated)?'COMPLETED':'PARTIALLY_DELIVERED',orderId])}await event(conn,'DeliveryConfirmed','dispatch_delivery_confirmation',header.insertId,userId,{shipment_id:shipmentId,delivered_at:deliveredAt.toISOString(),received_by:receivedBy,evidence_hash:sha256(evidenceSnapshot),shipment_status:shipmentStatus},{domain:'client',entity_type:'proof_of_delivery',entity_id:null});return{delivery_confirmation_id:header.insertId,shipment_id:shipmentId,shipment_status:shipmentStatus}})}

async function openException(payload,userId){const entityType=text(payload.entity_type,'entity_type',48),entityId=id(payload.entity_id,'entity_id'),type=text(payload.exception_type,'exception_type',64),severity=String(payload.severity||'MEDIUM').toUpperCase();if(!['LOW','MEDIUM','HIGH','CRITICAL'].includes(severity))throw new DispatchDeliveryError('INVALID_SEVERITY','Некорректная severity');return tx(async conn=>{const [r]=await conn.execute('INSERT INTO dispatch_exceptions(entity_type,entity_id,exception_type,severity,details_json,evidence_reference,opened_by_user_id) VALUES(?,?,?,?,?,?,?)',[entityType,entityId,type,severity,json(payload.details),payload.evidence_reference||null,actor(userId)]);await event(conn,'DispatchExceptionOpened','dispatch_exception',r.insertId,userId,{entity_type:entityType,entity_id:entityId,exception_type:type,severity});return{exception_id:r.insertId,status:'OPEN'}})}

module.exports={confirmDelivery,confirmPicking,createOrder,createPackage,createShipment,dispatchShipment,openException,packPackage,requestPicking,reviseShipment}
