const db=require('../../utils/db')
const {DispatchDeliveryError}=require('./domainError')
const {id,parseJson}=require('./helpers')
const parse=(row,fields)=>fields.reduce((out,k)=>({...out,[k]:parseJson(row[k],{})}),{...row})

async function readyToDispatch(){
 const [rows]=await db.execute(`SELECT c.id contract_commitment_id,c.contract_case_id,c.effective_contract_revision_id,c.quantity required_quantity,c.uom,c.fulfillment_status,c.commitment_hash,
  cc.contract_number,cc.client_id,cl.company_name client_name,c.subject_snapshot_json,c.delivery_snapshot_json,r.shipping_address_snapshot_json,r.client_contact_snapshot_json,
  COALESCE((SELECT SUM(a.allocated_quantity) FROM dispatch_order_allocations a JOIN dispatch_orders o ON o.id=a.dispatch_order_id WHERE a.contract_commitment_id=c.id AND o.status<>'CANCELLED'),0) allocated_quantity,
  COALESCE((SELECT SUM(dl.delivered_quantity) FROM dispatch_delivery_confirmation_lines dl JOIN dispatch_order_allocations a ON a.id=dl.dispatch_order_allocation_id JOIN dispatch_delivery_confirmations dc ON dc.id=dl.dispatch_delivery_confirmation_id WHERE a.contract_commitment_id=c.id AND dc.status='CONFIRMED'),0) delivered_quantity
  ,COALESCE((SELECT SUM(pc.quantity) FROM dispatch_package_contents pc JOIN dispatch_order_allocations a ON a.id=pc.dispatch_order_allocation_id JOIN dispatch_packages p ON p.id=pc.dispatch_package_id JOIN dispatch_shipment_packages sp ON sp.dispatch_package_id=p.id JOIN dispatch_shipments s ON s.id=sp.dispatch_shipment_id WHERE a.contract_commitment_id=c.id AND s.status IN ('DISPATCHED','IN_TRANSIT','PARTIALLY_DELIVERED','DELIVERED')),0) dispatched_quantity
  FROM contract_commitments c JOIN contract_cases cc ON cc.id=c.contract_case_id JOIN contract_revisions r ON r.id=c.effective_contract_revision_id JOIN clients cl ON cl.id=cc.client_id
  WHERE r.status='EFFECTIVE' AND c.commitment_type='SUPPLY' ORDER BY c.created_at,c.id`)
 const catalogIds=[...new Set(rows.map(row=>{const subject=parseJson(row.subject_snapshot_json,{});return Number(subject.catalog_position_id||subject.catalogPositionId)||null}).filter(Boolean))]
 const availableByCatalog=new Map()
 if(catalogIds.length){const [stock]=await db.execute(`SELECT u.catalog_position_id,COALESCE(SUM(CASE WHEN u.quality_status='RELEASED' AND u.status='ACTIVE' THEN state.physical_quantity-state.reserved_quantity ELSE 0 END),0) available_quantity
   FROM warehouse_stock_units u JOIN (SELECT stock_unit_id,SUM(quantity_delta) physical_quantity,SUM(reserved_delta) reserved_quantity FROM warehouse_inventory_movements GROUP BY stock_unit_id) state ON state.stock_unit_id=u.id
   WHERE u.catalog_position_id IN (${catalogIds.map(()=>'?').join(',')}) GROUP BY u.catalog_position_id`,catalogIds);for(const row of stock)availableByCatalog.set(Number(row.catalog_position_id),Number(row.available_quantity))}
 return rows.map(row=>{const destination=parseJson(row.shipping_address_snapshot_json,{}),subject=parseJson(row.subject_snapshot_json,{}),catalogId=Number(subject.catalog_position_id||subject.catalogPositionId)||null,required=Number(row.required_quantity),allocated=Number(row.allocated_quantity),delivered=Number(row.delivered_quantity),remaining=Math.max(0,required-allocated),available=catalogId?Number(availableByCatalog.get(catalogId)||0):0,blockers=[];if(!(destination.available===true||Object.keys(destination).some(k=>!['available','reason'].includes(k)&&destination[k])))blockers.push('DESTINATION_SNAPSHOT_REQUIRED');if(!catalogId)blockers.push('CATALOG_POSITION_UNRESOLVED');else if(available+0.0005<remaining)blockers.push('WAREHOUSE_STOCK_NOT_AVAILABLE');return{...row,subject_snapshot_json:subject,delivery_snapshot_json:parseJson(row.delivery_snapshot_json,{}),shipping_address_snapshot_json:destination,client_contact_snapshot_json:parseJson(row.client_contact_snapshot_json,{}),allocated_quantity:allocated,delivered_quantity:delivered,warehouse_available_quantity:available,remaining_to_allocate:remaining,fulfillment_projection:delivered<=0?'NOT_STARTED':delivered+0.0005>=required?'FULFILLED':'PARTIALLY_FULFILLED',blockers,dispatch_ready:blockers.length===0&&remaining>0}})
}

async function overview(){const [ready,orders,picking,packages,shipments,deliveries,exceptions]=await Promise.all([
 readyToDispatch(),db.execute(`SELECT o.*,cl.company_name client_name,COUNT(DISTINCT a.id) allocation_count,COALESCE(SUM(a.allocated_quantity),0) allocated_quantity,COALESCE((SELECT SUM(dl.delivered_quantity) FROM dispatch_delivery_confirmation_lines dl JOIN dispatch_order_allocations aa ON aa.id=dl.dispatch_order_allocation_id JOIN dispatch_delivery_confirmations dc ON dc.id=dl.dispatch_delivery_confirmation_id WHERE aa.dispatch_order_id=o.id AND dc.status='CONFIRMED'),0) delivered_quantity FROM dispatch_orders o JOIN clients cl ON cl.id=o.client_id LEFT JOIN dispatch_order_allocations a ON a.dispatch_order_id=o.id GROUP BY o.id ORDER BY o.updated_at DESC`).then(([x])=>x.map(r=>parse(r,['destination_snapshot_json','contact_snapshot_json','company_legal_snapshot_json','source_trace_snapshot_json']))),
 db.execute(`SELECT p.*,o.order_number,w.name warehouse_name,COUNT(l.id) line_count FROM dispatch_picking_requests p JOIN dispatch_orders o ON o.id=p.dispatch_order_id JOIN warehouse_locations w ON w.id=p.warehouse_id LEFT JOIN dispatch_picking_request_lines l ON l.dispatch_picking_request_id=p.id GROUP BY p.id ORDER BY p.requested_at DESC`).then(([x])=>x),
 db.execute(`SELECT p.*,o.order_number,COUNT(c.id) content_count,COALESCE(SUM(c.quantity),0) content_quantity FROM dispatch_packages p JOIN dispatch_orders o ON o.id=p.dispatch_order_id LEFT JOIN dispatch_package_contents c ON c.dispatch_package_id=p.id GROUP BY p.id ORDER BY p.updated_at DESC`).then(([x])=>x.map(r=>parse(r,['dimensions_snapshot_json','seals_snapshot_json']))),
 db.execute(`SELECT s.*,COUNT(sp.dispatch_package_id) package_count,COUNT(DISTINCT p.dispatch_order_id) order_count,GROUP_CONCAT(DISTINCT c.dispatch_order_allocation_id ORDER BY c.dispatch_order_allocation_id) allocation_ids,COALESCE(SUM(c.quantity),0) dispatched_quantity,COALESCE((SELECT SUM(dl.delivered_quantity) FROM dispatch_delivery_confirmation_lines dl JOIN dispatch_delivery_confirmations dc ON dc.id=dl.dispatch_delivery_confirmation_id WHERE dc.dispatch_shipment_id=s.id AND dc.status='CONFIRMED'),0) delivered_quantity FROM dispatch_shipments s LEFT JOIN dispatch_shipment_packages sp ON sp.dispatch_shipment_id=s.id LEFT JOIN dispatch_packages p ON p.id=sp.dispatch_package_id LEFT JOIN dispatch_package_contents c ON c.dispatch_package_id=p.id GROUP BY s.id ORDER BY s.updated_at DESC`).then(([x])=>x.map(r=>parse(r,['destination_snapshot_json','contact_snapshot_json','company_legal_snapshot_json','carrier_snapshot_json','tracking_snapshot_json','terms_snapshot_json']))),
 db.execute(`SELECT d.*,s.shipment_number,COUNT(l.id) line_count,COALESCE(SUM(l.delivered_quantity),0) delivered_quantity FROM dispatch_delivery_confirmations d JOIN dispatch_shipments s ON s.id=d.dispatch_shipment_id LEFT JOIN dispatch_delivery_confirmation_lines l ON l.dispatch_delivery_confirmation_id=d.id GROUP BY d.id ORDER BY d.delivered_at DESC`).then(([x])=>x.map(r=>parse(r,['evidence_snapshot_json']))),
 db.execute("SELECT * FROM dispatch_exceptions ORDER BY FIELD(status,'OPEN','ACKNOWLEDGED','RESOLVED','CANCELLED'),opened_at DESC").then(([x])=>x.map(r=>parse(r,['details_json']))),
 ]);return{ready_to_dispatch:ready,dispatch_orders:orders,picking,packages,shipments,delivery_confirmations:deliveries,exceptions,boundaries:{contract:'read_only_commitment_source',warehouse:'stock_truth_via_explicit_command_boundary',client:'immutable_site_and_contact_snapshots',finance:'not_owned',completion:'projection_only'},data_gate:{ready_count:ready.length,dispatchable_count:ready.filter(x=>x.dispatch_ready).length,target_stock_is_not_fabricated:true}}}

async function getOrder(orderIdInput){const orderId=id(orderIdInput,'order_id');const [[order]]=await db.execute('SELECT * FROM dispatch_orders WHERE id=?',[orderId]);if(!order)throw new DispatchDeliveryError('ORDER_NOT_FOUND','Dispatch Order не найден',404);const [allocations,picking,pickingLines,packages,events]=await Promise.all([db.execute('SELECT * FROM dispatch_order_allocations WHERE dispatch_order_id=? ORDER BY id',[orderId]).then(([x])=>x.map(r=>parse(r,['commitment_snapshot_json']))),db.execute('SELECT * FROM dispatch_picking_requests WHERE dispatch_order_id=? ORDER BY requested_at,id',[orderId]).then(([x])=>x),db.execute('SELECT l.* FROM dispatch_picking_request_lines l JOIN dispatch_picking_requests p ON p.id=l.dispatch_picking_request_id WHERE p.dispatch_order_id=? ORDER BY l.id',[orderId]).then(([x])=>x),db.execute('SELECT * FROM dispatch_packages WHERE dispatch_order_id=? ORDER BY created_at,id',[orderId]).then(([x])=>x),db.execute("SELECT * FROM dispatch_events WHERE (aggregate_type='dispatch_order' AND aggregate_id=?) OR JSON_EXTRACT(payload_json,'$.order_id')=? ORDER BY occurred_at,id",[orderId,orderId]).then(([x])=>x.map(r=>parse(r,['payload_json'])))]);return{order:parse(order,['destination_snapshot_json','contact_snapshot_json','company_legal_snapshot_json','source_trace_snapshot_json']),allocations,picking,picking_lines:pickingLines,packages,history:events}}
async function fulfillmentProjection(){const rows=await readyToDispatch();return rows.map(x=>({contract_commitment_id:x.contract_commitment_id,contract_case_id:x.contract_case_id,required_quantity:Number(x.required_quantity),dispatched_quantity:Number(x.dispatched_quantity),delivered_quantity:x.delivered_quantity,uom:x.uom,status:x.fulfillment_projection,source_event:'DeliveryConfirmed'}))}
async function history(query={}){const params=[];let where='';if(query.aggregate_type){where='WHERE aggregate_type=?';params.push(String(query.aggregate_type))}const [rows]=await db.execute(`SELECT * FROM dispatch_events ${where} ORDER BY occurred_at DESC,id DESC LIMIT 500`,params);return rows.map(r=>parse(r,['payload_json']))}
module.exports={fulfillmentProjection,getOrder,history,overview,readyToDispatch}
