const db=require('../../utils/db')
const {CompletionLifecycleError}=require('./domainError')
const {actor,id,json,key,sha256,text,version}=require('./helpers')
const readiness=require('./readinessService')

async function event(conn,caseId,revision,type,user,payload={},options={}){const hash=sha256({caseId,revision,type,payload,reason_code:options.reason_code||null,evidence_reference:options.evidence_reference||null});return conn.execute(`INSERT INTO completion_lifecycle_events
  (completion_case_id,lifecycle_revision_number,event_type,completion_snapshot_id,reason_code,explanation,evidence_reference,actor_user_id,payload_json,event_hash,idempotency_key)
  VALUES(?,?,?,?,?,?,?,?,?,?,?)`,[caseId,revision,type,options.snapshot_id||null,options.reason_code||null,options.explanation||null,options.evidence_reference||null,actor(user),json(payload),hash,options.idempotency_key||null])}

async function materializeCase(contractCaseIdInput,userId){const contractCaseId=id(contractCaseIdInput,'contract_case_id'),conn=await db.getConnection();try{await conn.beginTransaction();const [[existing]]=await conn.execute('SELECT * FROM completion_cases WHERE contract_case_id=? FOR UPDATE',[contractCaseId]);if(existing){await conn.commit();return{completion_case_id:existing.id,state:existing.lifecycle_state,already_exists:true}}const [[contract]]=await conn.execute(`SELECT id,aggregate_status FROM contract_cases WHERE id=? FOR UPDATE`,[contractCaseId]);if(!contract)throw new CompletionLifecycleError('CONTRACT_CASE_NOT_FOUND','Contract Case не найден',404);if(contract.aggregate_status!=='EFFECTIVE')throw new CompletionLifecycleError('EFFECTIVE_CONTRACT_REQUIRED','Completion Case создаётся только для EFFECTIVE Contract',409);const [[policy]]=await conn.execute(`SELECT r.id FROM completion_policies p JOIN completion_policy_revisions r ON r.id=p.current_revision_id WHERE p.case_type='STANDARD_SALES' AND p.status='ACTIVE' AND r.status='ACTIVE' ORDER BY p.id LIMIT 1`);if(!policy)throw new CompletionLifecycleError('ACTIVE_POLICY_REQUIRED','Active Closure Policy не найдена',409);const [insert]=await conn.execute(`INSERT INTO completion_cases(case_number,contract_case_id,completion_policy_revision_id,lifecycle_state) VALUES(?,?,?,'ACTIVE')`,[`COMP-${String(contractCaseId).padStart(8,'0')}`,contractCaseId,policy.id]);await event(conn,insert.insertId,1,'CompletionCaseMaterialized',userId,{contract_case_id:contractCaseId,policy_revision_id:policy.id});await conn.commit();return{completion_case_id:insert.insertId,state:'ACTIVE'}}catch(error){await conn.rollback();throw error}finally{conn.release()}}

async function persistEvaluation(conn,completionCase,evaluation,userId){const [insert]=await conn.execute(`INSERT INTO completion_evaluations
  (completion_case_id,lifecycle_revision_number,readiness_state,completion_policy_revision_id,policy_snapshot_json,policy_hash,source_snapshot_json,blockers_json,warnings_json,evaluation_hash,evaluated_by_user_id)
  VALUES(?,?,?,?,?,?,?,?,?,?,?)`,[completionCase.id,completionCase.lifecycle_revision_number,evaluation.state,evaluation.policy.id,json(evaluation.policy.snapshot),evaluation.policy.hash,json(evaluation.source_snapshot),json(evaluation.blockers),json(evaluation.warnings),evaluation.evaluation_hash,actor(userId)]);return insert.insertId}

async function evaluateCase(caseIdInput,userId){const caseId=id(caseIdInput,'completion_case_id'),conn=await db.getConnection();try{await conn.beginTransaction();const [[completionCase]]=await conn.execute('SELECT * FROM completion_cases WHERE id=? FOR UPDATE',[caseId]);if(!completionCase)throw new CompletionLifecycleError('COMPLETION_CASE_NOT_FOUND','Completion Case не найден',404);if(completionCase.lifecycle_state==='CLOSED')throw new CompletionLifecycleError('CLOSED_CASE_IMMUTABLE','Closed Case доступен только в historical view',409);const evaluation=await readiness.evaluate(conn,completionCase),evaluationId=await persistEvaluation(conn,completionCase,evaluation,userId),lifecycleState=evaluation.state==='READY_TO_CLOSE'?'READY_TO_CLOSE':'ACTIVE';await conn.execute('UPDATE completion_cases SET lifecycle_state=?,last_evaluation_id=?,row_version=row_version+1 WHERE id=?',[lifecycleState,evaluationId,caseId]);await event(conn,caseId,completionCase.lifecycle_revision_number,'ReadinessEvaluated',userId,{evaluation_id:evaluationId,state:evaluation.state,policy_hash:evaluation.policy.hash,evaluation_hash:evaluation.evaluation_hash,blocker_codes:evaluation.blockers.map(x=>x.code)});await conn.commit();return{completion_case_id:caseId,evaluation_id:evaluationId,state:evaluation.state,lifecycle_state:lifecycleState,policy:evaluation.policy,gates:evaluation.gates,blockers:evaluation.blockers,warnings:evaluation.warnings,evaluation_hash:evaluation.evaluation_hash,row_version:Number(completionCase.row_version)+1}}catch(error){await conn.rollback();throw error}finally{conn.release()}}

function buildSnapshot(completionCase,evaluation,closureSequence){const commitments=evaluation.source_snapshot.commitments||[],procurement=evaluation.source_snapshot.procurement||[],finance=evaluation.source_snapshot.finance||{},dispatch=evaluation.source_snapshot.dispatch||{},money=(list,amount,currency)=>Object.values(list.reduce((out,row)=>{const code=row[currency]||'UNSPECIFIED';out[code]??={currency:code,amount:0};out[code].amount+=Number(row[amount]||0);return out},{})).map(x=>({...x,amount:Number(x.amount.toFixed(4))}));const commercial=money(commitments,'line_total','currency'),procurementCost=money(procurement.map(x=>({...x,purchase_total:Number(x.purchase_quantity||0)*Number(x.purchase_unit_price||0)})),'purchase_total','purchase_currency');let margin=null;if(commercial.length===1&&procurementCost.length===1&&commercial[0].currency===procurementCost[0].currency)margin={currency:commercial[0].currency,amount:Number((commercial[0].amount-procurementCost[0].amount).toFixed(4)),logistics_cost_included:false};return{identity:{completion_case_id:Number(completionCase.id),contract_case_id:Number(completionCase.contract_case_id),closure_sequence:closureSequence,lifecycle_revision_number:Number(completionCase.lifecycle_revision_number)},after_sales_reference_hooks:{completion_case_id:Number(completionCase.id),contract_case_id:Number(completionCase.contract_case_id),closure_sequence:closureSequence,workflow_created:false},commercial_value:commercial,procurement_cost:procurementCost,logistics_cost:null,margin,dates:{contract_effective_at:evaluation.source_snapshot.contract.effective_at||null,final_confirmed_delivery_at:(dispatch.delivery_confirmations||[]).at(-1)?.delivered_at||null},counts:{commitments:commitments.length,purchase_orders:new Set(procurement.map(x=>x.po_id).filter(Boolean)).size,shipments:new Set((dispatch.delivery_confirmations||[]).map(x=>x.dispatch_shipment_id)).size,proofs_of_delivery:(dispatch.delivery_confirmations||[]).length},finance:{ap:finance.ap||[],ar:finance.ar||[]},closure:{state:evaluation.state,blockers:evaluation.blockers,warnings:evaluation.warnings,evaluation_hash:evaluation.evaluation_hash},source_snapshot:evaluation.source_snapshot}}

async function closeCase(caseIdInput,payload,userId){const caseId=id(caseIdInput,'completion_case_id'),requestKey=key(payload.idempotency_key),expectedVersion=version(payload.row_version),evidence=text(payload.closure_evidence_reference,'closure_evidence_reference'),conn=await db.getConnection();let rejection=null;try{await conn.beginTransaction();const [[duplicate]]=await conn.execute('SELECT id,completion_case_id,closure_sequence,snapshot_hash FROM completion_snapshots WHERE idempotency_key=? FOR UPDATE',[requestKey]);if(duplicate){await conn.commit();return{completion_case_id:duplicate.completion_case_id,snapshot_id:duplicate.id,closure_sequence:duplicate.closure_sequence,snapshot_hash:duplicate.snapshot_hash,state:'CLOSED',already_exists:true}}const [[completionCase]]=await conn.execute('SELECT * FROM completion_cases WHERE id=? FOR UPDATE',[caseId]);if(!completionCase)throw new CompletionLifecycleError('COMPLETION_CASE_NOT_FOUND','Completion Case не найден',404);if(completionCase.lifecycle_state==='CLOSED')throw new CompletionLifecycleError('CASE_ALREADY_CLOSED','Completion Case уже закрыт',409);if(Number(completionCase.row_version)!==expectedVersion)throw new CompletionLifecycleError('COMPLETION_STATE_CONFLICT','Completion state/version conflict',409,{actual_row_version:Number(completionCase.row_version)});const evaluation=await readiness.evaluate(conn,completionCase),evaluationId=await persistEvaluation(conn,completionCase,evaluation,userId);if(evaluation.state!=='READY_TO_CLOSE'){await conn.execute("UPDATE completion_cases SET lifecycle_state='ACTIVE',last_evaluation_id=?,row_version=row_version+1 WHERE id=?",[evaluationId,caseId]);await event(conn,caseId,completionCase.lifecycle_revision_number,'ClosureRejected',userId,{evaluation_id:evaluationId,policy_hash:evaluation.policy.hash,evaluation_hash:evaluation.evaluation_hash,blocker_codes:evaluation.blockers.map(x=>x.code)},{evidence_reference:evidence});await conn.commit();rejection=new CompletionLifecycleError('CASE_NOT_READY_TO_CLOSE','Completion Case не готов к закрытию',409,{evaluation_id:evaluationId,policy_hash:evaluation.policy.hash,blockers:evaluation.blockers,row_version:expectedVersion+1});return}
    const [[sequenceRow]]=await conn.execute('SELECT COALESCE(MAX(closure_sequence),0)+1 next_sequence FROM completion_snapshots WHERE completion_case_id=? FOR UPDATE',[caseId]),closureSequence=Number(sequenceRow.next_sequence),snapshot=buildSnapshot(completionCase,evaluation,closureSequence),snapshotHash=sha256({snapshot,traceability:evaluation.traceability,policy_hash:evaluation.policy.hash});const [snapshotInsert]=await conn.execute(`INSERT INTO completion_snapshots
      (completion_case_id,closure_sequence,lifecycle_revision_number,completion_evaluation_id,completion_policy_revision_id,policy_snapshot_json,policy_hash,completion_snapshot_json,traceability_snapshot_json,snapshot_hash,idempotency_key,closed_by_user_id)
      VALUES(?,?,?,?,?,?,?,?,?,?,?,?)`,[caseId,closureSequence,completionCase.lifecycle_revision_number,evaluationId,evaluation.policy.id,json(evaluation.policy.snapshot),evaluation.policy.hash,json(snapshot),json(evaluation.traceability),snapshotHash,requestKey,actor(userId)]);await event(conn,caseId,completionCase.lifecycle_revision_number,'CaseClosed',userId,{evaluation_id:evaluationId,snapshot_id:snapshotInsert.insertId,closure_sequence:closureSequence,policy_hash:evaluation.policy.hash,snapshot_hash:snapshotHash},{snapshot_id:snapshotInsert.insertId,evidence_reference:evidence,idempotency_key:`close-event:${sha256(requestKey)}`});await conn.execute("UPDATE completion_cases SET lifecycle_state='CLOSED',last_evaluation_id=?,latest_snapshot_id=?,closed_at=NOW(6),closed_by_user_id=?,row_version=row_version+1 WHERE id=?",[evaluationId,snapshotInsert.insertId,actor(userId),caseId]);await conn.commit();return{completion_case_id:caseId,state:'CLOSED',snapshot_id:snapshotInsert.insertId,closure_sequence:closureSequence,snapshot_hash:snapshotHash,policy_hash:evaluation.policy.hash,after_sales_reference_hooks:{completion_case_id:caseId,completion_snapshot_id:snapshotInsert.insertId,contract_case_id:Number(completionCase.contract_case_id),workflow_created:false},row_version:expectedVersion+1}}catch(error){await conn.rollback();throw error}finally{conn.release();if(rejection)throw rejection}}

async function reopenCase(caseIdInput,payload,userId){const caseId=id(caseIdInput,'completion_case_id'),requestKey=key(payload.idempotency_key),expectedVersion=version(payload.row_version),reasonCode=text(payload.reason_code,'reason_code',80),explanation=text(payload.explanation,'explanation',4000),evidence=text(payload.evidence_reference,'evidence_reference'),conn=await db.getConnection();try{await conn.beginTransaction();const [[duplicate]]=await conn.execute('SELECT * FROM completion_lifecycle_events WHERE idempotency_key=? FOR UPDATE',[requestKey]);if(duplicate){await conn.commit();return{completion_case_id:duplicate.completion_case_id,lifecycle_revision_number:duplicate.lifecycle_revision_number,state:'REOPENED',already_exists:true}}const [[completionCase]]=await conn.execute('SELECT * FROM completion_cases WHERE id=? FOR UPDATE',[caseId]);if(!completionCase)throw new CompletionLifecycleError('COMPLETION_CASE_NOT_FOUND','Completion Case не найден',404);if(completionCase.lifecycle_state!=='CLOSED'||!completionCase.latest_snapshot_id)throw new CompletionLifecycleError('CLOSED_CASE_REQUIRED','Reopen разрешён только для CLOSED Case',409);if(Number(completionCase.row_version)!==expectedVersion)throw new CompletionLifecycleError('COMPLETION_STATE_CONFLICT','Completion state/version conflict',409,{actual_row_version:Number(completionCase.row_version)});const revision=Number(completionCase.lifecycle_revision_number)+1;await event(conn,caseId,revision,'CaseReopened',userId,{previous_snapshot_id:completionCase.latest_snapshot_id,previous_lifecycle_revision_number:Number(completionCase.lifecycle_revision_number),snapshot_mutated:false},{snapshot_id:completionCase.latest_snapshot_id,reason_code:reasonCode,explanation,evidence_reference:evidence,idempotency_key:requestKey});await conn.execute("UPDATE completion_cases SET lifecycle_state='REOPENED',lifecycle_revision_number=?,closed_at=NULL,closed_by_user_id=NULL,row_version=row_version+1 WHERE id=?",[revision,caseId]);await conn.commit();return{completion_case_id:caseId,state:'REOPENED',lifecycle_revision_number:revision,previous_snapshot_id:completionCase.latest_snapshot_id,snapshot_mutated:false,row_version:expectedVersion+1}}catch(error){await conn.rollback();throw error}finally{conn.release()}}

module.exports={closeCase,evaluateCase,materializeCase,reopenCase}
