const db=require('../../utils/db')
const {CompletionLifecycleError}=require('./domainError')
const {id,parseJson}=require('./helpers')
const readiness=require('./readinessService')
const parse=(row,fields)=>{const result={...row};for(const field of fields)result[field]=parseJson(result[field],field.endsWith('s_json')?[]:{});return result}
async function overview(){const [cases]=await db.execute(`SELECT c.*,cc.contract_number,cc.aggregate_status,cl.company_name,p.policy_code,pr.revision_number policy_revision_number,pr.policy_hash,
    e.readiness_state last_readiness_state,e.blockers_json last_blockers_json,e.evaluated_at last_evaluated_at,s.snapshot_hash,s.closure_sequence
  FROM completion_cases c JOIN contract_cases cc ON cc.id=c.contract_case_id JOIN clients cl ON cl.id=cc.client_id
  JOIN completion_policy_revisions pr ON pr.id=c.completion_policy_revision_id JOIN completion_policies p ON p.id=pr.completion_policy_id
  LEFT JOIN completion_evaluations e ON e.id=c.last_evaluation_id LEFT JOIN completion_snapshots s ON s.id=c.latest_snapshot_id
  ORDER BY (c.lifecycle_state='CLOSED'),c.updated_at DESC LIMIT 200`);const [contractIntake]=await db.execute(`SELECT cc.id,cc.contract_number,cl.company_name,c.id completion_case_id,c.case_number
    FROM contract_cases cc JOIN clients cl ON cl.id=cc.client_id LEFT JOIN completion_cases c ON c.contract_case_id=cc.id
    WHERE cc.aggregate_status='EFFECTIVE' ORDER BY cc.updated_at DESC`);return{active_cases:cases.filter(x=>x.lifecycle_state!=='CLOSED').map(x=>parse(x,['last_blockers_json'])),closed_cases:cases.filter(x=>x.lifecycle_state==='CLOSED').map(x=>parse(x,['last_blockers_json'])),contract_intake:contractIntake,boundaries:{contract:'read_only_legal_and_commitment_evidence',procurement:'read_only_operational_readiness',warehouse:'read_only_stock_reservation_and_lineage_evidence',dispatch:'read_only_pod_confirmed_delivery',financial_operations:'read_only_independent_ap_ar_readiness',after_sales:'stable_reference_hooks_only_no_workflow',auto_close:false,legacy_inference:false}}
}
async function getCase(caseIdInput,{live=true}={}){const caseId=id(caseIdInput,'completion_case_id');const [[completionCase]]=await db.execute(`SELECT c.*,cc.contract_number,cc.aggregate_status,cl.company_name,p.policy_code,pr.revision_number policy_revision_number,pr.policy_hash
  FROM completion_cases c JOIN contract_cases cc ON cc.id=c.contract_case_id JOIN clients cl ON cl.id=cc.client_id JOIN completion_policy_revisions pr ON pr.id=c.completion_policy_revision_id JOIN completion_policies p ON p.id=pr.completion_policy_id WHERE c.id=?`,[caseId]);if(!completionCase)throw new CompletionLifecycleError('COMPLETION_CASE_NOT_FOUND','Completion Case не найден',404);const [evaluations,snapshots,events]=await Promise.all([db.execute('SELECT * FROM completion_evaluations WHERE completion_case_id=? ORDER BY evaluated_at DESC,id DESC',[caseId]).then(([x])=>x.map(r=>parse(r,['policy_snapshot_json','source_snapshot_json','blockers_json','warnings_json']))),db.execute('SELECT * FROM completion_snapshots WHERE completion_case_id=? ORDER BY closure_sequence DESC',[caseId]).then(([x])=>x.map(r=>parse(r,['policy_snapshot_json','completion_snapshot_json','traceability_snapshot_json']))),db.execute('SELECT * FROM completion_lifecycle_events WHERE completion_case_id=? ORDER BY occurred_at DESC,id DESC',[caseId]).then(([x])=>x.map(r=>parse(r,['payload_json'])))]);let current_readiness=null;if(live&&completionCase.lifecycle_state!=='CLOSED'){const evaluation=await readiness.evaluate(db,completionCase);current_readiness={state:evaluation.state,policy:evaluation.policy,gates:evaluation.gates,blockers:evaluation.blockers,warnings:evaluation.warnings,evaluation_hash:evaluation.evaluation_hash,recorded:false}}return{case:completionCase,current_readiness,evaluations,snapshots,lifecycle_history:events,after_sales_reference_hooks:{completion_case_id:caseId,completion_snapshot_id:completionCase.latest_snapshot_id||null,contract_case_id:Number(completionCase.contract_case_id),workflow_created:false}}}
async function history(query={}){const params=[];let where='';if(query.state){where='WHERE c.lifecycle_state=?';params.push(String(query.state).toUpperCase())}const [rows]=await db.execute(`SELECT c.id completion_case_id,c.case_number,c.lifecycle_state,c.lifecycle_revision_number,c.contract_case_id,cc.contract_number,cl.company_name,s.id snapshot_id,s.closure_sequence,s.snapshot_hash,s.policy_hash,s.closed_at
  FROM completion_cases c JOIN contract_cases cc ON cc.id=c.contract_case_id JOIN clients cl ON cl.id=cc.client_id LEFT JOIN completion_snapshots s ON s.completion_case_id=c.id ${where} ORDER BY COALESCE(s.closed_at,c.updated_at) DESC,c.id DESC,s.closure_sequence DESC LIMIT 500`,params);return{rows,closed_searchable:true,active_queue_excludes_closed:true}}
module.exports={getCase,history,overview}
