const db=require('../../utils/db')
const { ProcurementExecutionError }=require('./domainError')
const { actor,cleanText,event,parseJson,requestKey,sha256,toId }=require('./helpers')

const sourceSql=`SELECT cm.*,cr.status contract_revision_status,cc.contract_number,
 cal.source_pricing_decision_line_id,pdl.pricing_input_line_id,pil.sourcing_decision_line_id,
 sd.id sourcing_decision_id,sd.status sourcing_decision_status,sdl.supplier_offer_line_id,sdl.supplier_id,sdl.supplier_part_id,
 col.allocated_quantity,col.purchase_quantity,col.surplus_quantity,col.uom_snapshot,
 sol.supplier_part_number_snapshot,sol.description_snapshot,sol.moq,sol.pack_quantity,sol.unit_price purchase_unit_price,
 COALESCE(sol.currency,pil.purchase_currency) purchase_currency,sol.payment_terms,sol.incoterms,sol.incoterms_place,sol.validity_until,
 ps.name supplier_name,ps.public_code supplier_public_code,ps.country supplier_country,ps.website supplier_website,ps.risk_level supplier_risk_level,
 sp.supplier_part_number supplier_master_part_number
 FROM contract_commitments cm
 JOIN contract_revisions cr ON cr.id=cm.effective_contract_revision_id
 JOIN contract_cases cc ON cc.id=cm.contract_case_id
 JOIN commercial_accepted_lines cal ON cal.id=cm.source_accepted_line_id
 JOIN pricing_decision_lines pdl ON pdl.id=cal.source_pricing_decision_line_id
 JOIN pricing_input_lines pil ON pil.id=pdl.pricing_input_line_id
 JOIN sourcing_decision_lines sdl ON sdl.id=pil.sourcing_decision_line_id
 JOIN sourcing_decisions sd ON sd.id=sdl.sourcing_decision_id
 JOIN sourcing_coverage_option_lines col ON col.sourcing_coverage_option_id=sdl.sourcing_coverage_option_id AND col.sourcing_demand_id=sdl.sourcing_demand_id AND col.supplier_offer_line_id=sdl.supplier_offer_line_id
 JOIN supplier_offer_lines sol ON sol.id=sdl.supplier_offer_line_id
 JOIN part_suppliers ps ON ps.id=sdl.supplier_id
 LEFT JOIN supplier_parts sp ON sp.id=sdl.supplier_part_id`

async function createCase(payload,userId){
  const user=actor(userId),key=requestKey(payload.request_key),ids=[...new Set((payload.contract_commitment_ids||[]).map(toId).filter(Boolean))]
  if(!ids.length)throw new ProcurementExecutionError('COMMITMENTS_REQUIRED','Выберите effective Contract Commitments')
  const conn=await db.getConnection()
  try{
    await conn.beginTransaction()
    const [[existing]]=await conn.execute('SELECT * FROM procurement_execution_cases WHERE request_key=?',[key]);if(existing){await conn.commit();return { case_id:existing.id,case_number:existing.case_number,already_exists:true }}
    const [sources]=await conn.execute(`${sourceSql} WHERE cm.id IN (${ids.map(()=>'?').join(',')}) FOR UPDATE`,ids)
    if(sources.length!==ids.length)throw new ProcurementExecutionError('COMMITMENT_TRACE_INCOMPLETE','Не все commitments имеют полную immutable Contract → Pricing → Sourcing трассировку',409)
    const invalid=sources.filter(row=>row.contract_revision_status!=='EFFECTIVE'||row.sourcing_decision_status!=='finalized')
    if(invalid.length)throw new ProcurementExecutionError('SOURCE_NOT_EFFECTIVE','Допускаются только EFFECTIVE Contract и finalized Sourcing Decision',409,{ commitment_ids:invalid.map(x=>x.id) })
    const caseNumber=`PEX-${new Date().toISOString().replace(/\D/g,'').slice(0,14)}-${sha256(key).slice(0,6).toUpperCase()}`
    const [insert]=await conn.execute('INSERT INTO procurement_execution_cases (case_number,title,owner_user_id,request_key,created_by_user_id) VALUES (?,?,?,?,?)',[caseNumber,cleanText(payload.title)||`Execution for ${sources.map(x=>x.contract_number).join(', ')}`,toId(payload.owner_user_id)||user,key,user])
    for(const row of sources){
      const authoritativeUom=cleanText(row.uom_snapshot),originalUom=cleanText(row.uom)||'UNSPECIFIED'
      const resolvedUom=originalUom!=='UNSPECIFIED'?originalUom:(authoritativeUom&&authoritativeUom!=='UNSPECIFIED'?authoritativeUom:'UNSPECIFIED')
      const partNumber=cleanText(row.supplier_master_part_number)||cleanText(row.supplier_part_number_snapshot)
      const reasons=['SUPPLIER_RECONFIRMATION_REQUIRED'];if(resolvedUom==='UNSPECIFIED')reasons.push('AUTHORITATIVE_UOM_MISSING');if(!partNumber)reasons.push('SUPPLIER_PART_IDENTITY_MISSING')
      const supplier={ id:row.supplier_id,name:row.supplier_name,public_code:row.supplier_public_code,country:row.supplier_country,website:row.supplier_website,risk_level:row.supplier_risk_level }
      const part={ supplier_part_id:row.supplier_part_id,part_number:partNumber,source:row.supplier_part_id?'SUPPLIER_PART_MASTER':'IMMUTABLE_SUPPLIER_OFFER_SNAPSHOT',description:row.description_snapshot }
      const sourcingTrace={ sourcing_decision_id:row.sourcing_decision_id,sourcing_decision_line_id:row.sourcing_decision_line_id,supplier_offer_line_id:row.supplier_offer_line_id,coverage:{ allocated_quantity:row.allocated_quantity,purchase_quantity:row.purchase_quantity,excess_quantity:row.surplus_quantity,uom:row.uom_snapshot },offer:{ moq:row.moq,pack_quantity:row.pack_quantity,validity_until:row.validity_until } }
      const immutable={ commitment_id:row.id,commitment_hash:row.commitment_hash,contract_number:row.contract_number,contract_revision_id:row.effective_contract_revision_id,source_accepted_line_id:row.source_accepted_line_id }
      const sourceHash=sha256({immutable,sourcingTrace,supplier,part,purchase_unit_price:row.purchase_unit_price,currency:row.purchase_currency})
      const [itemInsert]=await conn.execute(`INSERT INTO procurement_execution_items
       (procurement_execution_case_id,contract_commitment_id,effective_contract_revision_id,sourcing_decision_id,sourcing_decision_line_id,supplier_offer_line_id,supplier_id,supplier_part_id,
        supplier_snapshot_json,supplier_part_snapshot_json,contract_trace_snapshot_json,sourcing_trace_snapshot_json,allocated_quantity,purchase_quantity,excess_quantity,uom,purchase_unit_price,purchase_currency,
        moq,pack_quantity,payment_terms,incoterms,incoterms_place,validity_until,readiness_reasons_json,source_hash)
       VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`,[insert.insertId,row.id,row.effective_contract_revision_id,row.sourcing_decision_id,row.sourcing_decision_line_id,row.supplier_offer_line_id,row.supplier_id,row.supplier_part_id,JSON.stringify(supplier),JSON.stringify(part),JSON.stringify(immutable),JSON.stringify(sourcingTrace),row.allocated_quantity,row.purchase_quantity,row.surplus_quantity,resolvedUom,row.purchase_unit_price,row.purchase_currency,row.moq,row.pack_quantity,row.payment_terms,row.incoterms,row.incoterms_place,row.validity_until,JSON.stringify(reasons),sourceHash])
      if(originalUom==='UNSPECIFIED'&&resolvedUom!=='UNSPECIFIED')await conn.execute(`INSERT INTO procurement_uom_resolutions (procurement_execution_item_id,original_uom,resolved_uom,authority_type,authority_entity_id,evidence_snapshot_json,resolved_by_user_id) VALUES (?,?,?,'SOURCING_COVERAGE_SNAPSHOT',?,?,?)`,[itemInsert.insertId,originalUom,resolvedUom,row.sourcing_decision_line_id,JSON.stringify({ sourcing_decision_id:row.sourcing_decision_id,sourcing_decision_line_id:row.sourcing_decision_line_id,coverage_uom:row.uom_snapshot,contract_uom:row.uom }),user])
    }
    await event(conn,insert.insertId,'ProcurementExecutionCaseCreated','procurement_execution_case',insert.insertId,user,{ commitment_ids:ids,upstream_writes:false })
    await conn.commit();return { case_id:insert.insertId,case_number:caseNumber,item_count:sources.length }
  }catch(error){await conn.rollback();throw error}finally{conn.release()}
}

function compareReconfirmation(item,confirmed){
  const differences=[]
  const numeric=new Set(['purchase_quantity','moq','pack_quantity','purchase_unit_price'])
  const add=(field,category,before,after)=>{const equal=numeric.has(field)?Number(before)===Number(after):String(before??'')===String(after??'');if(!equal)differences.push({field,category,before:before??null,after:after??null})}
  if(confirmed.available===false)return { status:'SUPPLY_FAILURE',differences:[{field:'available',category:'SUPPLY_FAILURE',before:true,after:false}] }
  add('supplier_id','SOURCING',item.supplier_id,confirmed.supplier_id??item.supplier_id)
  add('supplier_part_number','SOURCING',parseJson(item.supplier_part_snapshot_json).part_number,confirmed.supplier_part_number)
  for(const field of ['purchase_quantity','moq','pack_quantity','uom'])add(field,'SOURCING',item[field],confirmed[field])
  for(const field of ['purchase_unit_price','purchase_currency','payment_terms','incoterms'])add(field,'PRICING',item[field],confirmed[field])
  if(differences.some(x=>x.category==='SOURCING'))return { status:'SOURCING_UPDATE_REQUIRED',differences }
  if(differences.some(x=>x.category==='PRICING'))return { status:'PRICING_RECHECK_REQUIRED',differences }
  return { status:differences.length?'NON_MATERIAL_DIFFERENCE':'MATCHED',differences }
}

async function reconfirmItem(itemIdInput,payload,userId){
  const itemId=toId(itemIdInput),user=actor(userId),evidence=cleanText(payload.evidence_reference),confirmed=payload.confirmed||{}
  if(!itemId||!evidence)throw new ProcurementExecutionError('VALIDATION_ERROR','Item и evidence_reference обязательны')
  const conn=await db.getConnection();try{await conn.beginTransaction();const [[item]]=await conn.execute('SELECT * FROM procurement_execution_items WHERE id=? FOR UPDATE',[itemId]);if(!item)throw new ProcurementExecutionError('ITEM_NOT_FOUND','Procurement item не найден',404)
    const comparison=compareReconfirmation(item,confirmed);const [insert]=await conn.execute(`INSERT INTO procurement_supplier_reconfirmations (procurement_execution_item_id,status,confirmed_snapshot_json,comparison_snapshot_json,evidence_reference,evidence_hash,confirmed_by_user_id) VALUES (?,?,?,?,?,?,?)`,[itemId,comparison.status,JSON.stringify(confirmed),JSON.stringify(comparison),evidence,sha256({confirmed,evidence}),user])
    let readiness='READY',reasons=[]
    if(comparison.status==='SOURCING_UPDATE_REQUIRED'||comparison.status==='SUPPLY_FAILURE'){readiness='SOURCING_UPDATE_REQUIRED';reasons=[comparison.status]}
    else if(comparison.status==='PRICING_RECHECK_REQUIRED'){readiness='PRICING_RECHECK_REQUIRED';reasons=[comparison.status]}
    else {const part=parseJson(item.supplier_part_snapshot_json);if(item.uom==='UNSPECIFIED'||!part.part_number){readiness='BLOCKED';reasons.push(item.uom==='UNSPECIFIED'?'AUTHORITATIVE_UOM_MISSING':'SUPPLIER_PART_IDENTITY_MISSING')}if(!cleanText(confirmed.payment_terms??item.payment_terms)||!cleanText(confirmed.incoterms??item.incoterms)){readiness='BLOCKED';reasons.push('COMMERCIAL_TERMS_INCOMPLETE')}}
    await conn.execute('UPDATE procurement_execution_items SET readiness_status=?,readiness_reasons_json=?,row_version=row_version+1 WHERE id=?',[readiness,JSON.stringify(reasons),itemId])
    if(['SOURCING_UPDATE_REQUIRED','PRICING_RECHECK_REQUIRED'].includes(readiness)){const target=readiness.startsWith('SOURCING')?'SOURCING':'PRICING';await conn.execute(`INSERT INTO procurement_change_requests (procurement_execution_case_id,procurement_execution_item_id,target_domain,reason_code,before_snapshot_json,requested_change_json,evidence_snapshot_json,requested_by_user_id) VALUES (?,?,?,?,?,?,?,?)`,[item.procurement_execution_case_id,itemId,target,comparison.status,JSON.stringify({ source_hash:item.source_hash }),JSON.stringify(comparison.differences),JSON.stringify({ reconfirmation_id:insert.insertId,evidence_reference:evidence }),user]);await conn.execute("UPDATE procurement_execution_cases SET status='CHANGE_REQUIRED',row_version=row_version+1 WHERE id=?",[item.procurement_execution_case_id])}
    await event(conn,item.procurement_execution_case_id,'SupplierReconfirmationRecorded','procurement_supplier_reconfirmation',insert.insertId,user,{ status:comparison.status,readiness_status:readiness })
    await conn.commit();return { reconfirmation_id:insert.insertId,status:comparison.status,readiness_status:readiness,differences:comparison.differences }
  }catch(error){await conn.rollback();throw error}finally{conn.release()}}

async function generateCandidates(caseIdInput,userId){
  const caseId=toId(caseIdInput),user=actor(userId),conn=await db.getConnection();try{await conn.beginTransaction();const [[pc]]=await conn.execute('SELECT * FROM procurement_execution_cases WHERE id=? FOR UPDATE',[caseId]);if(!pc)throw new ProcurementExecutionError('CASE_NOT_FOUND','Procurement Execution Case не найден',404)
    const [items]=await conn.execute(`SELECT i.* FROM procurement_execution_items i LEFT JOIN procurement_po_candidate_items ci ON ci.procurement_execution_item_id=i.id WHERE i.procurement_execution_case_id=? AND i.readiness_status='READY' AND ci.procurement_execution_item_id IS NULL ORDER BY i.supplier_id,i.id`,[caseId]);if(!items.length)throw new ProcurementExecutionError('NO_READY_ITEMS','Нет READY items для PO candidates',409)
    const groups=new Map();for(const item of items){const snapshot={supplier_id:item.supplier_id,currency:item.purchase_currency,incoterms:item.incoterms,incoterms_place:item.incoterms_place,payment_terms:item.payment_terms,buyer_legal_entity:'CRUSHER_PARTS_DEFAULT'};const key=sha256(snapshot);if(!groups.has(key))groups.set(key,{snapshot,items:[]});groups.get(key).items.push(item)}
    const created=[];for(const [groupingKey,group] of groups){const code=`POC-${caseId}-${sha256(groupingKey+Date.now()).slice(0,8).toUpperCase()}`;const [insert]=await conn.execute('INSERT INTO procurement_po_candidates (procurement_execution_case_id,candidate_code,supplier_id,grouping_key,grouping_snapshot_json,created_by_user_id) VALUES (?,?,?,?,?,?)',[caseId,code,group.snapshot.supplier_id,groupingKey,JSON.stringify(group.snapshot),user]);for(const item of group.items)await conn.execute('INSERT INTO procurement_po_candidate_items (procurement_po_candidate_id,procurement_execution_item_id,source_snapshot_json) VALUES (?,?,?)',[insert.insertId,item.id,JSON.stringify({ source_hash:item.source_hash,readiness_status:item.readiness_status })]);created.push({candidate_id:insert.insertId,candidate_code:code,item_count:group.items.length})}
    await conn.execute("UPDATE procurement_execution_cases SET status='READY_FOR_PO',row_version=row_version+1 WHERE id=?",[caseId]);await event(conn,caseId,'POCandidatesGenerated','procurement_po_candidate',null,user,{ candidates:created });await conn.commit();return { candidates:created }
  }catch(error){await conn.rollback();throw error}finally{conn.release()}}

function legalBasis(payload){
  const type=payload.legal_basis_type
  if(type==='PURCHASE_ORDER_AS_CONTRACT'){const ready=Boolean(cleanText(payload.policy_reference)&&cleanText(payload.approval_reference));return {type,status:ready?'READY':'APPROVAL_REQUIRED',snapshot:{policy_reference:cleanText(payload.policy_reference),approval_reference:cleanText(payload.approval_reference),policy_version:cleanText(payload.policy_version),checked_at:new Date().toISOString()}}}
  if(type==='SUPPLIER_AGREEMENT'){let status='AGREEMENT_REQUIRED';if(payload.agreement_revision_id){status=payload.scope_match===false?'SCOPE_MISMATCH':(payload.valid_through&&new Date(payload.valid_through)<new Date()?'AGREEMENT_EXPIRED':'READY')}return {type,status,snapshot:{agreement_revision_id:toId(payload.agreement_revision_id),agreement_reference:cleanText(payload.agreement_reference),valid_through:payload.valid_through||null,scope_match:payload.scope_match!==false}}}
  throw new ProcurementExecutionError('LEGAL_BASIS_REQUIRED','Укажите Supplier Agreement или PURCHASE_ORDER_AS_CONTRACT policy evidence')
}

async function createPurchaseOrder(candidateIdInput,payload,userId){
  const paymentDueDate=cleanText(payload.payment_due_date)
  if(!/^\d{4}-\d{2}-\d{2}$/.test(paymentDueDate||''))throw new ProcurementExecutionError('PAYMENT_DUE_DATE_REQUIRED','Укажите календарный срок оплаты поставщику')
  const candidateId=toId(candidateIdInput),user=actor(userId),basis=legalBasis(payload),conn=await db.getConnection();try{await conn.beginTransaction();const [[candidate]]=await conn.execute("SELECT * FROM procurement_po_candidates WHERE id=? AND status='READY' FOR UPDATE",[candidateId]);if(!candidate)throw new ProcurementExecutionError('CANDIDATE_NOT_READY','PO Candidate не найден или уже использован',409)
    const [items]=await conn.execute(`SELECT i.* FROM procurement_po_candidate_items ci JOIN procurement_execution_items i ON i.id=ci.procurement_execution_item_id WHERE ci.procurement_po_candidate_id=? AND i.readiness_status='READY' ORDER BY i.id`,[candidateId]);if(!items.length)throw new ProcurementExecutionError('CANDIDATE_EMPTY','PO Candidate не содержит READY items',409)
    const poNumber=`PO-${new Date().getUTCFullYear()}-${String(candidate.id).padStart(6,'0')}`;const [orderInsert]=await conn.execute('INSERT INTO procurement_purchase_orders (po_number,procurement_execution_case_id,supplier_id,created_by_user_id) VALUES (?,?,?,?)',[poNumber,candidate.procurement_execution_case_id,candidate.supplier_id,user]);const first=items[0],supplier=parseJson(first.supplier_snapshot_json),group=parseJson(candidate.grouping_snapshot_json)
    const payment={terms:group.payment_terms,currency:group.currency,schedule_stages:[{stage_code:'FULL',calculation_type:'PERCENT',value:100,trigger_type:'CONFIRMED',trigger_offset_days:0,invoice_required:true,contractual_due_date:paymentDueDate,planned_payment_date:paymentDueDate,scope:{purchase_order:'FULL'}}]}
    const [revisionInsert]=await conn.execute(`INSERT INTO procurement_purchase_order_revisions (procurement_purchase_order_id,revision_number,supplier_snapshot_json,buyer_snapshot_json,delivery_snapshot_json,payment_snapshot_json,legal_basis_type,legal_basis_status,legal_basis_snapshot_json,presentation_snapshot_json,source_trace_snapshot_json,created_by_user_id) VALUES (?,1,?,?,?,?,?,?,?,?,?,?)`,[orderInsert.insertId,JSON.stringify(supplier),JSON.stringify(payload.buyer_snapshot||{legal_entity:'CRUSHER_PARTS_DEFAULT'}),JSON.stringify({incoterms:group.incoterms,place:group.incoterms_place,delivery_contact:cleanText(payload.delivery_contact)}),JSON.stringify(payment),basis.type,basis.status,JSON.stringify(basis.snapshot),JSON.stringify({supplier_contact:cleanText(payload.supplier_contact),comments:cleanText(payload.comments)}),JSON.stringify({candidate_id:candidateId,item_source_hashes:items.map(x=>x.source_hash)}),user])
    for(const [index,item] of items.entries()){const line={item_id:item.id,part:parseJson(item.supplier_part_snapshot_json),quantity:item.purchase_quantity,allocated:item.allocated_quantity,excess:item.excess_quantity,uom:item.uom,unit_price:item.purchase_unit_price,currency:item.purchase_currency,source:{contract:parseJson(item.contract_trace_snapshot_json),sourcing:parseJson(item.sourcing_trace_snapshot_json)}};await conn.execute(`INSERT INTO procurement_purchase_order_lines (procurement_purchase_order_revision_id,procurement_execution_item_id,line_number,supplier_part_snapshot_json,quantity,allocated_quantity,excess_quantity,uom,unit_price,currency,source_trace_snapshot_json,line_hash) VALUES (?,?,?,?,?,?,?,?,?,?,?,?)`,[revisionInsert.insertId,item.id,index+1,JSON.stringify(line.part),line.quantity,line.allocated,line.excess,line.uom,line.unit_price,line.currency,JSON.stringify(line.source),sha256(line)])}
    await conn.execute('UPDATE procurement_purchase_orders SET current_revision_id=? WHERE id=?',[revisionInsert.insertId,orderInsert.insertId]);await conn.execute("UPDATE procurement_po_candidates SET status='CONVERTED' WHERE id=?",[candidateId]);await conn.execute("UPDATE procurement_execution_cases SET status='PO_DRAFTING',row_version=row_version+1 WHERE id=?",[candidate.procurement_execution_case_id]);await event(conn,candidate.procurement_execution_case_id,'PurchaseOrderDraftCreated','procurement_purchase_order',orderInsert.insertId,user,{revision_id:revisionInsert.insertId,legal_basis_status:basis.status});await conn.commit();return { purchase_order_id:orderInsert.insertId,po_number:poNumber,revision_id:revisionInsert.insertId,legal_basis_status:basis.status }
  }catch(error){await conn.rollback();throw error}finally{conn.release()}}

async function updateDraftRevision(idInput,payload,userId){const id=toId(idInput),user=actor(userId);const allowed={supplier_contact:cleanText(payload.supplier_contact),delivery_contact:cleanText(payload.delivery_contact),comments:cleanText(payload.comments)};const conn=await db.getConnection();try{await conn.beginTransaction();const [[row]]=await conn.execute(`SELECT r.*,o.procurement_execution_case_id FROM procurement_purchase_order_revisions r JOIN procurement_purchase_orders o ON o.id=r.procurement_purchase_order_id WHERE r.id=? FOR UPDATE`,[id]);if(!row)throw new ProcurementExecutionError('REVISION_NOT_FOUND','PO revision не найдена',404);if(row.status!=='DRAFT')throw new ProcurementExecutionError('REVISION_IMMUTABLE','Issued и sent PO revisions неизменяемы',409);const presentation={...parseJson(row.presentation_snapshot_json),supplier_contact:allowed.supplier_contact,comments:allowed.comments};const delivery={...parseJson(row.delivery_snapshot_json),delivery_contact:allowed.delivery_contact};await conn.execute('UPDATE procurement_purchase_order_revisions SET presentation_snapshot_json=?,delivery_snapshot_json=? WHERE id=?',[JSON.stringify(presentation),JSON.stringify(delivery),id]);await event(conn,row.procurement_execution_case_id,'PurchaseOrderDraftPresentationUpdated','procurement_purchase_order_revision',id,user,{allowed_fields:Object.keys(allowed)});await conn.commit();return {revision_id:id,status:'DRAFT'} }catch(error){await conn.rollback();throw error}finally{conn.release()}}

async function createRevision(orderIdInput,payload,userId){
  const orderId=toId(orderIdInput),user=actor(userId),conn=await db.getConnection()
  try{
    await conn.beginTransaction()
    const [[order]]=await conn.execute('SELECT * FROM procurement_purchase_orders WHERE id=? FOR UPDATE',[orderId])
    if(!order)throw new ProcurementExecutionError('PURCHASE_ORDER_NOT_FOUND','Supplier PO не найден',404)
    const [[source]]=await conn.execute('SELECT * FROM procurement_purchase_order_revisions WHERE id=?',[order.current_revision_id])
    if(!source||!['ISSUED','SENT'].includes(source.status))throw new ProcurementExecutionError('LOCKED_REVISION_REQUIRED','Новая revision создаётся после issued/sent revision',409)
    const [[seq]]=await conn.execute('SELECT COALESCE(MAX(revision_number),0)+1 next_number FROM procurement_purchase_order_revisions WHERE procurement_purchase_order_id=?',[orderId])
    const basis=payload.legal_basis_type?legalBasis(payload):{type:source.legal_basis_type,status:source.legal_basis_status,snapshot:parseJson(source.legal_basis_snapshot_json)}
    const oldPresentation=parseJson(source.presentation_snapshot_json),oldDelivery=parseJson(source.delivery_snapshot_json)
    const presentation={...oldPresentation,comments:cleanText(payload.comments)||oldPresentation.comments}
    const delivery={...oldDelivery,delivery_contact:cleanText(payload.delivery_contact)||oldDelivery.delivery_contact}
    const [insert]=await conn.execute(`INSERT INTO procurement_purchase_order_revisions
      (procurement_purchase_order_id,revision_number,supplier_snapshot_json,buyer_snapshot_json,delivery_snapshot_json,payment_snapshot_json,
       legal_basis_type,legal_basis_status,legal_basis_snapshot_json,presentation_snapshot_json,source_trace_snapshot_json,supersedes_revision_id,created_by_user_id)
      VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)`,[orderId,seq.next_number,JSON.stringify(parseJson(source.supplier_snapshot_json)),JSON.stringify(parseJson(source.buyer_snapshot_json)),JSON.stringify(delivery),JSON.stringify(parseJson(source.payment_snapshot_json)),basis.type,basis.status,JSON.stringify(basis.snapshot),JSON.stringify(presentation),JSON.stringify(parseJson(source.source_trace_snapshot_json)),source.id,user])
    const [lines]=await conn.execute('SELECT * FROM procurement_purchase_order_lines WHERE procurement_purchase_order_revision_id=? ORDER BY line_number',[source.id])
    for(const line of lines)await conn.execute(`INSERT INTO procurement_purchase_order_lines
      (procurement_purchase_order_revision_id,procurement_execution_item_id,line_number,supplier_part_snapshot_json,quantity,allocated_quantity,excess_quantity,uom,unit_price,currency,source_trace_snapshot_json,line_hash)
      VALUES (?,?,?,?,?,?,?,?,?,?,?,?)`,[insert.insertId,line.procurement_execution_item_id,line.line_number,JSON.stringify(parseJson(line.supplier_part_snapshot_json)),line.quantity,line.allocated_quantity,line.excess_quantity,line.uom,line.unit_price,line.currency,JSON.stringify(parseJson(line.source_trace_snapshot_json)),line.line_hash])
    await conn.execute("UPDATE procurement_purchase_order_revisions SET status='SUPERSEDED' WHERE id=?",[source.id])
    await conn.execute("UPDATE procurement_purchase_orders SET current_revision_id=?,status='DRAFT',row_version=row_version+1 WHERE id=?",[insert.insertId,orderId])
    await event(conn,order.procurement_execution_case_id,'PurchaseOrderRevisionCreated','procurement_purchase_order_revision',insert.insertId,user,{supersedes_revision_id:source.id,core_lines_copied_unchanged:true})
    await conn.commit();return {revision_id:insert.insertId,revision_number:Number(seq.next_number),status:'DRAFT'}
  }catch(error){await conn.rollback();throw error}finally{conn.release()}
}

async function issueRevision(idInput,payload,userId){const id=toId(idInput),user=actor(userId),conn=await db.getConnection();try{await conn.beginTransaction();const [[r]]=await conn.execute(`SELECT r.*,o.po_number,o.procurement_execution_case_id,o.id order_id FROM procurement_purchase_order_revisions r JOIN procurement_purchase_orders o ON o.id=r.procurement_purchase_order_id WHERE r.id=? FOR UPDATE`,[id]);if(!r)throw new ProcurementExecutionError('REVISION_NOT_FOUND','PO revision не найдена',404);if(r.status!=='DRAFT')throw new ProcurementExecutionError('REVISION_NOT_DRAFT','Только draft revision можно issue',409);if(r.legal_basis_status!=='READY')throw new ProcurementExecutionError('LEGAL_BASIS_NOT_READY','Legal basis не готов',409,{status:r.legal_basis_status});const [lines]=await conn.execute('SELECT * FROM procurement_purchase_order_lines WHERE procurement_purchase_order_revision_id=? ORDER BY line_number',[id]);const blockers=[];if(!lines.length)blockers.push('LINES_REQUIRED');if(lines.some(x=>x.uom==='UNSPECIFIED'))blockers.push('AUTHORITATIVE_UOM_REQUIRED');if(blockers.length)throw new ProcurementExecutionError('PO_NOT_READY','PO не готов к issue',409,{blockers});const supplier=parseJson(r.supplier_snapshot_json),content={po_number:r.po_number,revision:r.revision_number,supplier,buyer:parseJson(r.buyer_snapshot_json),delivery:parseJson(r.delivery_snapshot_json),payment:parseJson(r.payment_snapshot_json),legal_basis:parseJson(r.legal_basis_snapshot_json),presentation:parseJson(r.presentation_snapshot_json),lines:lines.map(x=>({line_number:x.line_number,part:parseJson(x.supplier_part_snapshot_json),quantity:x.quantity,uom:x.uom,unit_price:x.unit_price,currency:x.currency}))};if(JSON.stringify(content).match(/client_name|margin|client_price/i))throw new ProcurementExecutionError('SUPPLIER_SAFE_PROJECTION_FAILED','Supplier document содержит запрещённые client/internal поля',409);const hash=sha256(content);await conn.execute("UPDATE procurement_purchase_order_revisions SET status='ISSUED',content_hash=?,issued_by_user_id=?,issued_at=NOW(6) WHERE id=?",[hash,user,id]);const [doc]=await conn.execute("INSERT INTO procurement_purchase_order_documents (procurement_purchase_order_revision_id,document_type,format,content_snapshot_json,document_hash,file_reference,generated_by_user_id) VALUES (?,'ISSUED_PO','JSON',?,?,?,?)",[id,JSON.stringify(content),hash,cleanText(payload.file_reference),user]);await conn.execute("UPDATE procurement_purchase_orders SET status='ISSUED',row_version=row_version+1 WHERE id=?",[r.order_id]);await event(conn,r.procurement_execution_case_id,'PurchaseOrderIssued','procurement_purchase_order_revision',id,user,{document_id:doc.insertId,content_hash:hash});await conn.commit();return {revision_id:id,status:'ISSUED',document_id:doc.insertId,content_hash:hash} }catch(error){await conn.rollback();throw error}finally{conn.release()}}

async function sendRevision(idInput,payload,userId){const id=toId(idInput),user=actor(userId),evidence=cleanText(payload.evidence_reference),recipients=Array.isArray(payload.recipients)?payload.recipients.map(cleanText).filter(Boolean):[];if(!evidence||!recipients.length)throw new ProcurementExecutionError('SEND_EVIDENCE_REQUIRED','Recipients и evidence_reference обязательны');const conn=await db.getConnection();try{await conn.beginTransaction();const [[r]]=await conn.execute(`SELECT r.*,o.procurement_execution_case_id,o.id order_id FROM procurement_purchase_order_revisions r JOIN procurement_purchase_orders o ON o.id=r.procurement_purchase_order_id WHERE r.id=? FOR UPDATE`,[id]);if(!r)throw new ProcurementExecutionError('REVISION_NOT_FOUND','PO revision не найдена',404);if(r.status==='SENT'){const [[existing]]=await conn.execute('SELECT * FROM procurement_purchase_order_sends WHERE procurement_purchase_order_revision_id=?',[id]);await conn.commit();return {send_id:existing.id,status:'SENT',already_exists:true}}if(r.status!=='ISSUED')throw new ProcurementExecutionError('REVISION_NOT_ISSUED','Сначала issue PO revision',409);const [[doc]]=await conn.execute("SELECT * FROM procurement_purchase_order_documents WHERE procurement_purchase_order_revision_id=? AND document_type='ISSUED_PO' ORDER BY id DESC LIMIT 1",[id]);if(!doc)throw new ProcurementExecutionError('ISSUED_DOCUMENT_REQUIRED','Issued document отсутствует',409);const sentAt=payload.sent_at?new Date(payload.sent_at):new Date();const [insert]=await conn.execute(`INSERT INTO procurement_purchase_order_sends (procurement_purchase_order_revision_id,procurement_purchase_order_document_id,channel,recipient_snapshot_json,evidence_reference,payload_hash,sent_by_user_id,sent_at) VALUES (?,?,?,?,?,?,?,?)`,[id,doc.id,cleanText(payload.channel)||'MANUAL',JSON.stringify(recipients),evidence,doc.document_hash,user,sentAt]);await conn.execute("UPDATE procurement_purchase_order_revisions SET status='SENT' WHERE id=?",[id]);await conn.execute("UPDATE procurement_purchase_orders SET status='AWAITING_CONFIRMATION',row_version=row_version+1 WHERE id=?",[r.order_id]);await conn.execute("UPDATE procurement_execution_cases SET status='AWAITING_CONFIRMATION',row_version=row_version+1 WHERE id=?",[r.procurement_execution_case_id]);await event(conn,r.procurement_execution_case_id,'PurchaseOrderSent','procurement_purchase_order_revision',id,user,{send_id:insert.insertId,payload_hash:doc.document_hash});await conn.commit();return {send_id:insert.insertId,status:'SENT'} }catch(error){await conn.rollback();throw error}finally{conn.release()}}

function discrepancy(poLine,confirmed){if(confirmed.available===false)return 'SUPPLY_FAILURE';const part=parseJson(poLine.supplier_part_snapshot_json);if(cleanText(confirmed.supplier_part_number)!==cleanText(part.part_number)||cleanText(confirmed.uom)!==cleanText(poLine.uom))return 'TECHNICAL';if(Number(confirmed.quantity)!==Number(poLine.quantity))return 'QUANTITY';if(Number(confirmed.unit_price)!==Number(poLine.unit_price)||cleanText(confirmed.currency)!==cleanText(poLine.currency))return 'COMMERCIAL';return 'NONE'}
async function registerConfirmation(revisionIdInput,payload,userId){const revisionId=toId(revisionIdInput),user=actor(userId),ref=cleanText(payload.confirmation_reference),evidence=cleanText(payload.evidence_reference),inputLines=Array.isArray(payload.lines)?payload.lines:[];if(!ref||!evidence||!inputLines.length)throw new ProcurementExecutionError('CONFIRMATION_EVIDENCE_REQUIRED','Reference, evidence и lines обязательны');const conn=await db.getConnection();try{await conn.beginTransaction();const [[r]]=await conn.execute(`SELECT r.*,o.procurement_execution_case_id,o.id order_id FROM procurement_purchase_order_revisions r JOIN procurement_purchase_orders o ON o.id=r.procurement_purchase_order_id WHERE r.id=? FOR UPDATE`,[revisionId]);if(!r||r.status!=='SENT')throw new ProcurementExecutionError('SENT_REVISION_REQUIRED','Confirmation сравнивается только с SENT PO revision',409);const [poLines]=await conn.execute('SELECT * FROM procurement_purchase_order_lines WHERE procurement_purchase_order_revision_id=? ORDER BY line_number',[revisionId]);if(inputLines.length!==poLines.length)throw new ProcurementExecutionError('CONFIRMATION_LINE_COUNT_MISMATCH','Confirmation должна покрывать все SENT PO lines',409);const [insert]=await conn.execute(`INSERT INTO procurement_supplier_confirmations (procurement_purchase_order_revision_id,confirmation_reference,evidence_reference,evidence_hash,received_by_user_id,received_at) VALUES (?,?,?,?,?,?)`,[revisionId,ref,evidence,sha256({ref,evidence,lines:inputLines}),user,payload.received_at?new Date(payload.received_at):new Date()]);const classes=[];for(const poLine of poLines){const confirmed=inputLines.find(x=>Number(x.po_line_id)===Number(poLine.id)||Number(x.line_number)===Number(poLine.line_number));if(!confirmed)throw new ProcurementExecutionError('CONFIRMATION_LINE_MISSING',`Отсутствует confirmation line ${poLine.line_number}`,409);const classification=discrepancy(poLine,confirmed);classes.push(classification);await conn.execute('INSERT INTO procurement_supplier_confirmation_lines (procurement_supplier_confirmation_id,procurement_purchase_order_line_id,confirmed_snapshot_json,comparison_snapshot_json,discrepancy_class) VALUES (?,?,?,?,?)',[insert.insertId,poLine.id,JSON.stringify(confirmed),JSON.stringify({sent:{quantity:poLine.quantity,uom:poLine.uom,unit_price:poLine.unit_price,currency:poLine.currency,part:parseJson(poLine.supplier_part_snapshot_json)},classification}),classification])}
    const status=classes.every(x=>x==='NONE'||x==='NON_MATERIAL')?'MATCHED':'DISCREPANCY';await conn.execute('UPDATE procurement_supplier_confirmations SET status=? WHERE id=?',[status,insert.insertId]);if(status==='DISCREPANCY'){const target=classes.some(x=>['TECHNICAL','QUANTITY','SUPPLY_FAILURE'].includes(x))?'SOURCING':'PRICING';await conn.execute(`INSERT INTO procurement_change_requests (procurement_execution_case_id,target_domain,reason_code,before_snapshot_json,requested_change_json,evidence_snapshot_json,requested_by_user_id) VALUES (?,?,?,?,?,?,?)`,[r.procurement_execution_case_id,target,'SUPPLIER_CONFIRMATION_DISCREPANCY',JSON.stringify({po_revision_id:revisionId,content_hash:r.content_hash}),JSON.stringify({classes}),JSON.stringify({confirmation_id:insert.insertId,evidence_reference:evidence}),user]);await conn.execute("UPDATE procurement_purchase_orders SET status='CHANGE_REQUIRED' WHERE id=?",[r.order_id]);await conn.execute("UPDATE procurement_execution_cases SET status='CHANGE_REQUIRED' WHERE id=?",[r.procurement_execution_case_id])}
    await event(conn,r.procurement_execution_case_id,'SupplierConfirmationReceived','procurement_supplier_confirmation',insert.insertId,user,{status,classes});await conn.commit();return {confirmation_id:insert.insertId,status,discrepancy_classes:classes}
  }catch(error){await conn.rollback();throw error}finally{conn.release()}}

async function acceptConfirmation(idInput,userId){const id=toId(idInput),user=actor(userId),conn=await db.getConnection();try{await conn.beginTransaction();const [[c]]=await conn.execute(`SELECT c.*,r.procurement_purchase_order_id,o.procurement_execution_case_id FROM procurement_supplier_confirmations c JOIN procurement_purchase_order_revisions r ON r.id=c.procurement_purchase_order_revision_id JOIN procurement_purchase_orders o ON o.id=r.procurement_purchase_order_id WHERE c.id=? FOR UPDATE`,[id]);if(!c)throw new ProcurementExecutionError('CONFIRMATION_NOT_FOUND','Confirmation не найдена',404);if(c.status!=='ACCEPTED'&&c.status!=='MATCHED')throw new ProcurementExecutionError('CONFIRMATION_HAS_MATERIAL_DISCREPANCY','Принимать можно только соответствующее заказу подтверждение',409);if(c.status==='MATCHED'){await conn.execute("UPDATE procurement_supplier_confirmations SET status='ACCEPTED',accepted_by_user_id=?,accepted_at=NOW(6) WHERE id=?",[user,id]);await conn.execute("UPDATE procurement_purchase_orders SET status='CONFIRMED',row_version=row_version+1 WHERE id=?",[c.procurement_purchase_order_id]);await event(conn,c.procurement_execution_case_id,'SupplierConfirmationAccepted','procurement_supplier_confirmation',id,user,{finance_objects_created:false,warehouse_objects_created:false})}const [[pending]]=await conn.execute("SELECT COUNT(*) count FROM procurement_purchase_orders WHERE procurement_execution_case_id=? AND status<>'CONFIRMED'",[c.procurement_execution_case_id]);if(!Number(pending.count))await conn.execute("UPDATE procurement_execution_cases SET status='CONFIRMED',row_version=row_version+1 WHERE id=?",[c.procurement_execution_case_id]);await conn.commit();return {confirmation_id:id,status:'ACCEPTED',already_exists:c.status==='ACCEPTED',finance_objects_created:false,warehouse_objects_created:false} }catch(error){await conn.rollback();throw error}finally{conn.release()}}

module.exports={ acceptConfirmation,createCase,createPurchaseOrder,createRevision,generateCandidates,issueRevision,reconfirmItem,registerConfirmation,sendRevision,updateDraftRevision }
