const CAPABILITY_DEFINITIONS = [
  {
    key: 'catalogs.lookup',
    name: 'Справочный доступ к каталогам',
    description: 'Поиск и чтение мастер-данных без полного редактирования',
    section: 'catalogs',
    sort_order: 10,
  },
  {
    key: 'catalogs.edit',
    name: 'Полное редактирование каталогов',
    description: 'Редактирование каталогов напрямую',
    section: 'catalogs',
    sort_order: 20,
  },
  {
    key: 'workflow.rfq.master_data.write',
    name: 'Изменение мастер-данных из RFQ',
    description: 'Создание и правка supplier parts, цен и связанных данных внутри RFQ-процесса',
    section: 'workflow',
    sort_order: 30,
  },
  {
    key: 'workflow.client.master_data.write',
    name: 'Изменение клиентских данных из раздела Заявки клиентов',
    description: 'Правка клиентов, контактов и реквизитов из клиентского процесса',
    section: 'workflow',
    sort_order: 40,
  },
  {
    key: 'workflow.sales_quotes.manage',
    name: 'Управление КП',
    description: 'Создание и изменение коммерческих предложений и ревизий',
    section: 'workflow',
    sort_order: 50,
  },
  {
    key: 'workflow.contracts.manage',
    name: 'Управление контрактами',
    description: 'Создание и изменение контрактов',
    section: 'workflow',
    sort_order: 60,
  },
  {
    key: 'workflow.purchase_orders.manage',
    name: 'Управление заказами поставщикам',
    description: 'Создание и изменение заказов поставщикам',
    section: 'workflow',
    sort_order: 70,
  },
  {
    key: 'admin.users_roles.manage',
    name: 'Управление пользователями и ролями',
    description: 'Администрирование пользователей, ролей и прав',
    section: 'administration',
    sort_order: 80,
  },
  {
    key: 'administration.access',
    name: 'Доступ к администрированию',
    description: 'Просмотр рабочей зоны Administration',
    section: 'administration',
    sort_order: 800,
  },
  {
    key: 'administration.users.manage',
    name: 'Управление пользователями',
    description: 'Управление учетными записями и их состоянием',
    section: 'administration',
    sort_order: 810,
  },
  {
    key: 'administration.roles.manage',
    name: 'Управление ролями и полномочиями',
    description: 'Настройка ролей и capability-наборов',
    section: 'administration',
    sort_order: 820,
  },
  {
    key: 'administration.audit.view',
    name: 'Просмотр аудита безопасности',
    description: 'Просмотр событий безопасности и изменений доступа',
    section: 'administration',
    sort_order: 830,
  },
  {
    key: 'administration.sessions.manage',
    name: 'Управление сессиями',
    description: 'Просмотр и принудительное завершение сессий',
    section: 'administration',
    sort_order: 840,
  },
  ...[
    ['client_requests.access', 'Доступ к заявкам клиентов', 'Просмотр рабочей зоны заявок клиентов', 900],
    ['client_requests.create', 'Создание заявок клиентов', 'Создание заявки и первой ревизии', 910],
    ['client_requests.edit_header', 'Редактирование заявки', 'Изменение контекста и заголовка заявки', 920],
    ['client_requests.manage_revisions', 'Управление ревизиями заявки', 'Создание и финализация клиентских ревизий', 930],
    ['client_requests.identify_items', 'Идентификация позиций', 'Связывание строк заявки с Classifier/Catalog Position', 940],
    ['client_requests.manage_requirements', 'Требования к закупке', 'Фиксация допустимых замен и технических требований', 950],
    ['client_requests.release_to_procurement', 'Передача в закупку', 'Создание неизменяемого Procurement Release', 960],
    ['client_requests.archive', 'Архивирование заявок', 'Архивирование заявки без удаления истории', 970],
  ].map(([key, name, description, sort_order]) => ({
    key,
    name,
    description,
    section: 'client_requests',
    sort_order,
  })),
  ...[
    ['technical_identification.access', 'Просмотр очереди идентификации', 'Очередь и история технической идентификации', 980],
    ['technical_identification.manage', 'Работа с идентификацией', 'Взятие задач в работу, уточнения и возврат в очередь', 981],
    ['technical_identification.assign', 'Назначение идентификации', 'Исполнитель, приоритет и срок задач идентификации', 982],
    ['technical_identification.resolve', 'Решение идентификации', 'Транзакционное связывание задачи с Catalog Position', 983],
  ].map(([key, name, description, sort_order]) => ({
    key,
    name,
    description,
    section: 'technical_identification',
    sort_order,
  })),
  ...[
    ['sourcing.access', 'Просмотр Sourcing', 'Доступ к очереди и read model Sourcing Case', 1000],
    ['sourcing.cases.manage', 'Управление Sourcing Case', 'Создание, принятие и архивирование кейсов', 1010],
    ['sourcing.inquiries.manage', 'Управление Supplier Inquiry', 'Ревизии и dispatch запросов поставщикам', 1020],
    ['sourcing.offers.manage', 'Управление Supplier Offer', 'Транзакционный ввод предложений поставщиков', 1030],
    ['sourcing.coverage.manage', 'Управление покрытием', 'Создание и проверка вариантов покрытия', 1040],
    ['sourcing.decisions.finalize', 'Финализация Sourcing Decision', 'Неизменяемое решение по покрытию', 1050],
    ['sourcing.master_data_promotion.request', 'Запрос на продвижение мастер-данных', 'Проверяемый запрос без прямой записи Supplier master data', 1060],
  ].map(([key, name, description, sort_order]) => ({
    key,
    name,
    description,
    section: 'sourcing',
    sort_order,
  })),
  ...[
    ['pricing.access', 'Просмотр Pricing', 'Доступ к очереди и проекциям Pricing Case', 1100],
    ['pricing.cases.manage', 'Управление Pricing Case', 'Прием immutable Sourcing Decision и фиксация входа', 1110],
    ['pricing.groups.manage', 'Управление расчетными группами', 'Создание Calculation Group и Route Variant', 1120],
    ['pricing.calculate', 'Выполнение расчета', 'Создание неизменяемых Calculation Revision', 1130],
    ['pricing.client_prices.manage', 'Управление ценами клиента', 'Утверждение расчетных цен и запрос override', 1140],
    ['pricing.overrides.approve', 'Согласование ценовых отклонений', 'Approve/reject обоснованных price override', 1150],
    ['pricing.decisions.finalize', 'Финализация Pricing Decision', 'Фиксация неизменяемой ревизии решения Pricing', 1160],
    ['pricing.costs.view', 'Просмотр внутренней себестоимости', 'Доступ к purchase/landed/internal cost projection', 1170],
    ['pricing.supplier_identity.reveal', 'Раскрытие поставщика в Pricing', 'Явный доступ к реальному Supplier identity с аудитом', 1180],
  ].map(([key, name, description, sort_order]) => ({
    key,
    name,
    description,
    section: 'pricing',
    sort_order,
  })),
  ...[
    ['commercial_offers.access', 'Просмотр Commercial Offer', 'Доступ к очереди и seller-safe проекциям предложений', 1200],
    ['commercial_offers.manage', 'Управление Commercial Offer', 'Создание из fixed Pricing Decision и редактирование draft revision', 1210],
    ['commercial_offers.approvals.request', 'Запрос Commercial approval', 'Создание обоснованного запроса исключения', 1220],
    ['commercial_offers.approvals.decide', 'Решение Commercial approval', 'Approve/reject/return коммерческого исключения', 1230],
    ['commercial_offers.issue', 'Выпуск Commercial Offer', 'Readiness, rendering и immutable send snapshot', 1240],
    ['commercial_offers.feedback.manage', 'Регистрация ответа клиента', 'Structured feedback и Change Impact Assessment', 1250],
    ['commercial_offers.accept', 'Фиксация принятого предложения', 'Создание immutable Accepted Commercial Revision', 1260],
  ].map(([key, name, description, sort_order]) => ({
    key,
    name,
    description,
    section: 'commercial_offers',
    sort_order,
  })),
  ...[
    ['contracts.access', 'Просмотр Contract', 'Доступ к очереди и Contract Case workspace', 1300],
    ['contracts.manage', 'Управление Contract', 'Создание из immutable acceptance и редактирование draft revision', 1310],
    ['contracts.legal_review', 'Legal review Contract', 'Юридические terms, clauses и deviations', 1320],
    ['contracts.approvals.request', 'Запрос Contract approval', 'Создание обоснованного запроса согласования', 1330],
    ['contracts.approvals.decide', 'Решение Contract approval', 'Approve, reject или return юридического отклонения', 1340],
    ['contracts.documents.manage', 'Документы Contract', 'Генерация и регистрация immutable document evidence', 1350],
    ['contracts.send_external', 'Отправка Contract', 'Фиксация внешней отправки и блокировка revision', 1360],
    ['contracts.sign', 'Подписание Contract', 'Регистрация provider-neutral signature evidence', 1370],
    ['contracts.make_effective', 'Ввод Contract в силу', 'Создание immutable Contract Commitments', 1380],
  ].map(([key, name, description, sort_order]) => ({ key,name,description,section:'contracts',sort_order })),
  ...[
    ['procurement_execution.access','Просмотр Procurement Execution','Очередь readiness, commitments, PO и confirmations',1400],
    ['procurement_execution.manage','Управление Procurement Execution','Приём effective Contract Commitments и readiness',1410],
    ['procurement_execution.reconfirm','Reconfirmation поставщика','Фиксация immutable supplier reconfirmation evidence',1420],
    ['procurement_execution.change_requests','Upstream change request','Явный возврат без cross-domain write',1430],
    ['procurement_purchase_orders.manage','Управление Supplier PO','PO candidates и draft revisions',1440],
    ['procurement_purchase_orders.legal_basis','Проверка legal basis PO','Agreement либо PO-as-contract evidence',1450],
    ['procurement_purchase_orders.issue','Выпуск Supplier PO','Immutable issue и send evidence',1460],
    ['procurement_purchase_orders.confirmations','Supplier confirmations','Регистрация и сравнение confirmation',1470],
    ['procurement_purchase_orders.confirmations.accept','Принятие supplier confirmation','SupplierConfirmationAccepted без finance objects',1480],
  ].map(([key,name,description,sort_order])=>({key,name,description,section:'procurement_execution',sort_order})),
  ...[
    ['financial_operations.access','Просмотр Financial Operations','Доступ к operational AP/AR workspace и read models',1500],
    ['financial_operations.ap.manage','Управление AP commitments','Материализация payment schedule только из accepted supplier confirmation',1510],
    ['financial_operations.ap.invoices','Supplier invoices и allocations','Регистрация supplier invoice, matching и allocations',1520],
    ['financial_operations.ap.payments','Supplier payments и allocations','Регистрация и allocation supplier payments',1530],
    ['financial_operations.ap.disputes','Финансовые споры','Регистрация и управление supplier invoice disputes',1540],
    ['financial_operations.ar.manage','Управление operational AR','Материализация receivables из effective Contract commitments',1550],
    ['financial_operations.ar.payments','Customer payments и allocations','Регистрация и allocation customer payments',1560],
    ['financial_operations.adjustments','Financial corrections','Auditable approved adjustments and reversals',1570],
    ['financial_operations.forecast.view','Financial forecast','Payment calendar, exposure и forecast read models',1580],
    ['financial_operations.completion.view','Finance readiness projection','Финансовая готовность без записи в Completion',1590],
  ].map(([key,name,description,sort_order])=>({key,name,description,section:'financial_operations',sort_order})),
  ...[
    ['warehouse_inventory.access','Просмотр Warehouse & Inventory','Доступ к warehouse workspace и read models',1600],
    ['warehouse_inventory.master_data.manage','Склады и места хранения','Управление физическими складами и местами хранения',1610],
    ['warehouse_inventory.inbound.manage','Ожидаемые поставки','Expected inbound только из accepted supplier confirmation',1620],
    ['warehouse_inventory.receiving','Приёмка','Фиксация фактической приёмки и Stock Unit lineage',1630],
    ['warehouse_inventory.movements','Перемещения и put-away','Auditable движения Stock Unit',1640],
    ['warehouse_inventory.reservations','Резервы','First-class reservation и release',1650],
    ['warehouse_inventory.quality','Warehouse quality hold','Operational hold/release without separate QMS',1660],
    ['warehouse_inventory.counts','Инвентаризация','Blind count и recount workflow',1670],
    ['warehouse_inventory.adjustments','Складские корректировки','Approved compensating adjustments',1680],
    ['warehouse_inventory.availability.view','Просмотр доступности','Physical, held, reserved and available projections',1690],
    ['warehouse_inventory.history.view','История склада','Movement and evidence history',1700],
  ].map(([key,name,description,sort_order])=>({key,name,description,section:'warehouse_inventory',sort_order})),
  ...[
    ['dispatch_delivery.access','Просмотр Dispatch & Delivery','Ready, dispatch, shipment and delivery read models',1720],
    ['dispatch_delivery.orders.manage','Dispatch Orders','Dispatch Orders from immutable Contract Commitments',1730],
    ['dispatch_delivery.picking.manage','Picking','Warehouse picking request and evidence',1740],
    ['dispatch_delivery.packages.manage','Packages','Package content with Stock Unit lineage',1750],
    ['dispatch_delivery.shipments.manage','Shipments','Shipment planning, snapshots and consolidation',1760],
    ['dispatch_delivery.shipments.dispatch','Shipment dispatch','Exactly-once Warehouse issue',1770],
    ['dispatch_delivery.delivery.confirm','Delivery Confirmation','POD and delivered quantity mapping',1780],
    ['dispatch_delivery.exceptions.manage','Dispatch exceptions','Auditable exception management',1790],
    ['dispatch_delivery.history.view','Dispatch history','Append-only dispatch history',1800],
  ].map(([key,name,description,sort_order])=>({key,name,description,section:'dispatch_delivery',sort_order})),
  ...[
    ['completion.access','Просмотр Completion & Lifecycle','Active, ready, closed and historical completion cases',1820],
    ['completion.readiness.evaluate','Оценка closure readiness','Persist deterministic policy-based readiness evaluation',1830],
    ['completion.close','Закрытие case','Explicit atomic close with immutable completion snapshot',1840],
    ['completion.reopen','Исключительное reopen','Audited exceptional reopen without snapshot mutation',1850],
    ['completion.history.view','История Completion','Snapshots, policy evidence and lifecycle revisions',1860],
  ].map(([key,name,description,sort_order])=>({key,name,description,section:'completion',sort_order})),
  ...[
    ['after_sales.access','Просмотр After Sales','Open, active, closed claims and traceability',1880],
    ['after_sales.manage','Управление claims','Create claims and manage owned lifecycle',1890],
    ['after_sales.investigate','Evidence и investigation','Append-only evidence, notes and findings',1900],
    ['after_sales.resolve','Resolution и handoff','Resolution classification and explicit external-domain handoff',1910],
    ['after_sales.close','Закрытие и reopen claim','Audited close and reopen without upstream mutation',1920],
    ['after_sales.history.view','История After Sales','Append-only claim history and historical search',1930],
  ].map(([key,name,description,sort_order])=>({key,name,description,section:'after_sales',sort_order})),
]

const ROLE_CAPABILITY_PRESETS = {
  admin: CAPABILITY_DEFINITIONS.map((item) => item.key),
  prodavec: [
    'catalogs.lookup',
    'workflow.client.master_data.write',
    'workflow.sales_quotes.manage',
    'workflow.contracts.manage',
    'client_requests.access',
    'client_requests.create',
    'client_requests.edit_header',
    'client_requests.manage_revisions',
    'client_requests.identify_items',
    'client_requests.manage_requirements',
    'client_requests.release_to_procurement',
    'client_requests.archive',
    'technical_identification.access',
    'sourcing.access',
    'pricing.access',
    'pricing.client_prices.manage',
    'pricing.decisions.finalize',
    'commercial_offers.access',
    'commercial_offers.manage',
    'commercial_offers.approvals.request',
    'commercial_offers.issue',
    'commercial_offers.feedback.manage',
    'commercial_offers.accept',
    'contracts.access',
    'contracts.manage',
    'contracts.legal_review',
    'contracts.approvals.request',
    'contracts.documents.manage',
    'contracts.send_external',
    'contracts.sign',
    'procurement_execution.access',
    'financial_operations.access','financial_operations.forecast.view','financial_operations.completion.view',
    'warehouse_inventory.access','warehouse_inventory.availability.view','warehouse_inventory.history.view',
    'dispatch_delivery.access','dispatch_delivery.history.view',
    'completion.access','completion.readiness.evaluate','completion.close','completion.history.view',
    'after_sales.access','after_sales.manage','after_sales.history.view',
  ],
  zakupshchik: [
    'catalogs.lookup',
    'workflow.rfq.master_data.write',
    'workflow.purchase_orders.manage',
    'client_requests.access',
    'technical_identification.access',
    'sourcing.access',
    'sourcing.cases.manage',
    'sourcing.inquiries.manage',
    'sourcing.offers.manage',
    'sourcing.coverage.manage',
    'sourcing.master_data_promotion.request',
    'pricing.access',
    'pricing.cases.manage',
    'pricing.groups.manage',
    'pricing.calculate',
    'pricing.costs.view',
    'pricing.supplier_identity.reveal',
    'commercial_offers.access',
    'contracts.access',
    'procurement_execution.access','procurement_execution.manage','procurement_execution.reconfirm','procurement_execution.change_requests',
    'procurement_purchase_orders.manage','procurement_purchase_orders.issue','procurement_purchase_orders.confirmations',
    'financial_operations.access','financial_operations.forecast.view','financial_operations.completion.view',
    'warehouse_inventory.access','warehouse_inventory.inbound.manage','warehouse_inventory.availability.view','warehouse_inventory.history.view',
    'dispatch_delivery.access','dispatch_delivery.history.view',
    'completion.access','completion.history.view',
  ],
  'nachalnik-otdela-zakupok': [
    'catalogs.lookup',
    'catalogs.edit',
    'workflow.rfq.master_data.write',
    'workflow.client.master_data.write',
    'workflow.sales_quotes.manage',
    'workflow.contracts.manage',
    'workflow.purchase_orders.manage',
    'admin.users_roles.manage',
    'administration.access',
    'administration.users.manage',
    'administration.roles.manage',
    'administration.audit.view',
    'administration.sessions.manage',
    'client_requests.access',
    'client_requests.create',
    'client_requests.edit_header',
    'client_requests.manage_revisions',
    'client_requests.identify_items',
    'client_requests.manage_requirements',
    'client_requests.release_to_procurement',
    'client_requests.archive',
    'technical_identification.access',
    'technical_identification.manage',
    'technical_identification.assign',
    'technical_identification.resolve',
    'sourcing.access',
    'sourcing.cases.manage',
    'sourcing.inquiries.manage',
    'sourcing.offers.manage',
    'sourcing.coverage.manage',
    'sourcing.decisions.finalize',
    'sourcing.master_data_promotion.request',
    'pricing.access',
    'pricing.cases.manage',
    'pricing.groups.manage',
    'pricing.calculate',
    'pricing.client_prices.manage',
    'pricing.overrides.approve',
    'pricing.decisions.finalize',
    'pricing.costs.view',
    'pricing.supplier_identity.reveal',
    'commercial_offers.access',
    'commercial_offers.manage',
    'commercial_offers.approvals.request',
    'commercial_offers.approvals.decide',
    'commercial_offers.issue',
    'commercial_offers.feedback.manage',
    'commercial_offers.accept',
    'contracts.access',
    'contracts.manage',
    'contracts.legal_review',
    'contracts.approvals.request',
    'contracts.approvals.decide',
    'contracts.documents.manage',
    'contracts.send_external',
    'contracts.sign',
    'contracts.make_effective',
    'procurement_execution.access','procurement_execution.manage','procurement_execution.reconfirm','procurement_execution.change_requests',
    'procurement_purchase_orders.manage','procurement_purchase_orders.legal_basis','procurement_purchase_orders.issue',
    'procurement_purchase_orders.confirmations','procurement_purchase_orders.confirmations.accept',
    ...CAPABILITY_DEFINITIONS.filter((item) => item.section === 'financial_operations').map((item) => item.key),
    ...CAPABILITY_DEFINITIONS.filter((item) => item.section === 'warehouse_inventory').map((item) => item.key),
    ...CAPABILITY_DEFINITIONS.filter((item) => item.section === 'dispatch_delivery').map((item) => item.key),
    ...CAPABILITY_DEFINITIONS.filter((item) => item.section === 'completion').map((item) => item.key),
    ...CAPABILITY_DEFINITIONS.filter((item) => item.section === 'after_sales').map((item) => item.key),
  ],
  'specialist-po-katalogam': [
    'catalogs.lookup',
    'catalogs.edit',
    'client_requests.access',
    'client_requests.identify_items',
    'technical_identification.access',
    'technical_identification.manage',
    'technical_identification.assign',
    'technical_identification.resolve',
    'sourcing.access',
    'pricing.access',
    'commercial_offers.access',
    'contracts.access',
    'procurement_execution.access',
    'warehouse_inventory.access','warehouse_inventory.availability.view','warehouse_inventory.history.view',
    'dispatch_delivery.access','dispatch_delivery.history.view',
    'completion.access','completion.history.view',
    'after_sales.access','after_sales.history.view',
  ],
  nablyudatel: [
    'catalogs.lookup',
    'client_requests.access',
    'technical_identification.access',
    'sourcing.access',
    'pricing.access',
    'commercial_offers.access',
    'contracts.access',
    'procurement_execution.access',
    'financial_operations.access','financial_operations.forecast.view','financial_operations.completion.view',
    'warehouse_inventory.access','warehouse_inventory.availability.view','warehouse_inventory.history.view',
    'dispatch_delivery.access','dispatch_delivery.history.view',
    'completion.access','completion.history.view',
    'after_sales.access','after_sales.history.view',
  ],
  finansist: [
    ...CAPABILITY_DEFINITIONS.filter((item) => item.section === 'financial_operations').map((item) => item.key),
    'completion.access','completion.history.view',
  ],
  kladovshchik: [
    ...CAPABILITY_DEFINITIONS.filter((item) => item.section === 'warehouse_inventory').map((item) => item.key),
    'dispatch_delivery.access','dispatch_delivery.picking.manage','dispatch_delivery.packages.manage','dispatch_delivery.history.view',
    'completion.access','completion.history.view',
  ],
  logist: [
    ...CAPABILITY_DEFINITIONS.filter((item) => item.section === 'dispatch_delivery').map((item) => item.key),
    'completion.access','completion.history.view',
  ],
  'specialist-po-reklamatsiyam': CAPABILITY_DEFINITIONS.filter((item) => item.section === 'after_sales').map((item) => item.key),
}

const uniqueKeys = (values) => [...new Set((values || []).map((value) => String(value)))]

const buildPresetApplicationPlan = ({ activeCapabilityKeys, presetKeys, definitionKeys } = {}) => {
  const active = uniqueKeys(activeCapabilityKeys)
  const preset = uniqueKeys(presetKeys)
  const definitions = uniqueKeys(definitionKeys || CAPABILITY_DEFINITIONS.map((item) => item.key))
  const activeSet = new Set(active)
  const definitionSet = new Set(definitions)

  const activeMissingFromCode = active.filter((key) => !definitionSet.has(key))
  const codeMissingFromDatabase = definitions.filter((key) => !activeSet.has(key))
  const presetMissingFromDatabase = preset.filter((key) => !activeSet.has(key))
  const duplicateDefinitionKeys = CAPABILITY_DEFINITIONS
    .map((item) => item.key)
    .filter((key, index, keys) => keys.indexOf(key) !== index)
  const duplicatePresetKeys = (presetKeys || [])
    .map((key) => String(key))
    .filter((key, index, keys) => keys.indexOf(key) !== index)

  return {
    ok: !activeMissingFromCode.length && !codeMissingFromDatabase.length &&
      !presetMissingFromDatabase.length && !duplicateDefinitionKeys.length && !duplicatePresetKeys.length,
    activeMissingFromCode,
    codeMissingFromDatabase,
    presetMissingFromDatabase,
    duplicateDefinitionKeys: uniqueKeys(duplicateDefinitionKeys),
    duplicatePresetKeys: uniqueKeys(duplicatePresetKeys),
    appliedCapabilityKeys: preset,
  }
}

module.exports = {
  CAPABILITY_DEFINITIONS,
  ROLE_CAPABILITY_PRESETS,
  buildPresetApplicationPlan,
}
