const UNIT_ALIASES = new Map(
  Object.entries({
    pcs: 'шт',
    pc: 'шт',
    piece: 'шт',
    pieces: 'шт',
    ea: 'шт',
    each: 'шт',
    шт: 'шт',
    'шт.': 'шт',
    штук: 'шт',
    штука: 'шт',
    штуки: 'шт',
    set: 'компл',
    kit: 'компл',
    комплект: 'компл',
    компл: 'компл',
    'компл.': 'компл',
    kg: 'кг',
    kilogram: 'кг',
    kilo: 'кг',
    кг: 'кг',
    'кг.': 'кг',
    g: 'г',
    gram: 'г',
    грамм: 'г',
    г: 'г',
    'г.': 'г',
    t: 'т',
    ton: 'т',
    tonne: 'т',
    тонна: 'т',
    т: 'т',
    'т.': 'т',
    m: 'м',
    meter: 'м',
    metre: 'м',
    метр: 'м',
    м: 'м',
    cm: 'см',
    centimeter: 'см',
    centimetre: 'см',
    сантиметр: 'см',
    см: 'см',
    mm: 'мм',
    millimeter: 'мм',
    millimetre: 'мм',
    миллиметр: 'мм',
    мм: 'мм',
    m2: 'м²',
    'm²': 'м²',
    м2: 'м²',
    'м²': 'м²',
    m3: 'м³',
    'm³': 'м³',
    м3: 'м³',
    'м³': 'м³',
    l: 'л',
    liter: 'л',
    litre: 'л',
    литр: 'л',
    л: 'л',
    'л.': 'л',
    day: 'дн',
    days: 'дн',
    день: 'дн',
    дн: 'дн',
    'дн.': 'дн',
    kw: 'квт',
    kilowatt: 'квт',
    киловатт: 'квт',
    квт: 'квт',
    'квт.': 'квт',
    v: 'в',
    volt: 'в',
    вольт: 'в',
    в: 'в',
    'в.': 'в',
    hz: 'гц',
    hertz: 'гц',
    герц: 'гц',
    гц: 'гц',
    'гц.': 'гц',
    rpm: 'об/мин',
    'r/min': 'об/мин',
    'rev/min': 'об/мин',
    'об/мин': 'об/мин',
    'об/мин.': 'об/мин',
    a: 'а',
    ampere: 'а',
    ампер: 'а',
    а: 'а',
    nm: 'нм',
    'n·m': 'нм',
    'n*m': 'нм',
    'н·м': 'нм',
    нм: 'нм',
    bar: 'бар',
    бар: 'бар',
    mpa: 'мпа',
    мпа: 'мпа',
    tph: 'т/ч',
    't/h': 'т/ч',
    'т/час': 'т/ч',
    'т/ч': 'т/ч',
    celsius: '°c',
    '°c': '°c',
    '℃': '°c',
    degree: 'град',
    degrees: 'град',
    deg: 'град',
    град: 'град',
    'град.': 'град',
    percent: '%',
    '%': '%',
    процент: '%',
  })
)

const normalizeCode = (value) => {
  if (value === undefined || value === null) return null
  const key = String(value).trim().toLowerCase()
  if (!key) return null
  return UNIT_ALIASES.get(key) || key
}

const isUnitCode = (value) => /^[^\s]{1,32}$/.test(String(value || ''))

function normalizeUom(value, { allowEmpty = true } = {}) {
  if (value === undefined || value === null || String(value).trim() === '') {
    return { uom: allowEmpty ? null : undefined, error: null }
  }
  const code = normalizeCode(value)
  if (isUnitCode(code)) return { uom: code, error: null }
  return { uom: null, error: `Некорректная единица измерения: ${value}` }
}

module.exports = { UNIT_ALIASES, isUnitCode, normalizeCode, normalizeUom }
