const {AfterSalesError}=require('./domainError')
const TRANSITIONS={
  DRAFT:['OPEN','CANCELLED'],OPEN:['UNDER_REVIEW','AWAITING_INFORMATION','INVESTIGATION','REJECTED','CANCELLED'],
  UNDER_REVIEW:['AWAITING_INFORMATION','INVESTIGATION','RESOLUTION_PROPOSED','REJECTED','CANCELLED'],
  AWAITING_INFORMATION:['UNDER_REVIEW','INVESTIGATION','CANCELLED'],INVESTIGATION:['AWAITING_INFORMATION','UNDER_REVIEW','RESOLUTION_PROPOSED','REJECTED','CANCELLED'],
  RESOLUTION_PROPOSED:['INVESTIGATION','RESOLVED','REJECTED','CANCELLED'],RESOLVED:['CLOSED'],CLOSED:['UNDER_REVIEW'],REJECTED:['UNDER_REVIEW'],CANCELLED:['UNDER_REVIEW'],
}
function assertTransition(from,to){const target=String(to||'').toUpperCase();if(!TRANSITIONS[from]?.includes(target))throw new AfterSalesError('INVALID_STATUS_TRANSITION',`Переход ${from} → ${target||'EMPTY'} запрещён`,409,{allowed:TRANSITIONS[from]||[]});return target}
module.exports={TRANSITIONS,assertTransition}
