const db=require('../../utils/db')
const {AfterSalesError}=require('./domainError')
const {id,parseJson,toId}=require('./helpers')
const parse=(row,fields)=>{const out={...row};for(const field of fields)out[field]=parseJson(out[field],field.endsWith('s_json')?[]:{});return out}

async function overview(query={}){const params=[];let where='';if(toId(query.client_id)){where='WHERE c.client_id=?';params.push(toId(query.client_id))}const [rows]=await db.execute(`SELECT c.*,cl.company_name,cc.contract_number,cc.aggregate_status contract_status,comp.lifecycle_state completion_state,r.classification resolution_classification,r.status resolution_status,
  (SELECT COUNT(*) FROM after_sales_case_lines l WHERE l.after_sales_case_id=c.id) affected_line_count,
  (SELECT COUNT(*) FROM after_sales_evidence e WHERE e.after_sales_case_id=c.id) evidence_count
  FROM after_sales_cases c JOIN clients cl ON cl.id=c.client_id JOIN contract_cases cc ON cc.id=c.contract_case_id
  LEFT JOIN completion_cases comp ON comp.id=c.completion_case_id LEFT JOIN after_sales_resolutions r ON r.id=c.current_resolution_id
  ${where} ORDER BY (c.status IN ('CLOSED','REJECTED','CANCELLED')),c.updated_at DESC LIMIT 500`,params);return{open_claims:rows.filter(x=>!['CLOSED','REJECTED','CANCELLED'].includes(x.status)),closed_historical:rows.filter(x=>['CLOSED','REJECTED','CANCELLED'].includes(x.status)),boundaries:{entry:'KNOWN_CLIENT_AND_CONTRACT',contract:'READ_ONLY_NEVER_AUTO_REOPENED',completion:'READ_ONLY_NEVER_AUTO_REOPENED_OR_SNAPSHOT_MUTATED',dispatch:'READ_ONLY_CONFIRMED_DELIVERY_EVIDENCE',warehouse:'READ_ONLY_STOCK_UNIT_AND_RECEIPT_LINEAGE',procurement:'READ_ONLY_PO_LINE_AND_SUPPLIER_TRACE',classifier:'READ_ONLY_PROTECTED_MASTER_DATA',finance:'EXTERNAL_EXECUTION_ONLY',replacement:'EXPLICIT_HANDOFF_TO_EXISTING_CHAIN_NO_PARALLEL_RMA',qms_capa:false,auto_reopen:false}}
}

async function getCase(caseIdInput){const caseId=id(caseIdInput,'case_id');const [[claim]]=await db.execute(`SELECT c.*,cl.company_name,cc.contract_number,cc.aggregate_status contract_status,cc.row_version contract_row_version,comp.case_number completion_case_number,comp.lifecycle_state completion_state,comp.row_version completion_row_version,cs.snapshot_hash completion_snapshot_hash
  FROM after_sales_cases c JOIN clients cl ON cl.id=c.client_id JOIN contract_cases cc ON cc.id=c.contract_case_id
  LEFT JOIN completion_cases comp ON comp.id=c.completion_case_id LEFT JOIN completion_snapshots cs ON cs.id=c.completion_snapshot_id WHERE c.id=?`,[caseId]);if(!claim)throw new AfterSalesError('AFTER_SALES_CASE_NOT_FOUND','After Sales Case не найден',404)
  const [lines,evidence,investigation,resolutions,escalations,handoffs,events]=await Promise.all([
    db.execute('SELECT * FROM after_sales_case_lines WHERE after_sales_case_id=? ORDER BY id',[caseId]).then(([x])=>x.map(r=>parse(r,['source_snapshot_json','trace_gaps_json']))),
    db.execute('SELECT * FROM after_sales_evidence WHERE after_sales_case_id=? ORDER BY added_at,id',[caseId]).then(([x])=>x.map(r=>parse(r,['evidence_snapshot_json']))),
    db.execute('SELECT * FROM after_sales_investigation_entries WHERE after_sales_case_id=? ORDER BY recorded_at,id',[caseId]).then(([x])=>x.map(r=>parse(r,['details_json','evidence_references_json']))),
    db.execute('SELECT * FROM after_sales_resolutions WHERE after_sales_case_id=? ORDER BY revision_number',[caseId]).then(([x])=>x.map(r=>parse(r,['resolution_snapshot_json']))),
    db.execute(`SELECT e.*,s.company_name supplier_name,po.po_number,wr.receipt_number FROM after_sales_supplier_escalations e JOIN part_suppliers s ON s.id=e.supplier_id JOIN procurement_purchase_order_lines pol ON pol.id=e.procurement_purchase_order_line_id JOIN procurement_purchase_order_revisions por ON por.id=pol.procurement_purchase_order_revision_id JOIN procurement_purchase_orders po ON po.id=por.procurement_purchase_order_id JOIN warehouse_receipt_lines wrl ON wrl.id=e.warehouse_receipt_line_id JOIN warehouse_receipts wr ON wr.id=wrl.warehouse_receipt_id WHERE e.after_sales_case_id=? ORDER BY e.opened_at,e.id`,[caseId]).then(([x])=>x.map(r=>parse(r,['source_snapshot_json']))),
    db.execute('SELECT * FROM after_sales_downstream_handoffs WHERE after_sales_case_id=? ORDER BY requested_at,id',[caseId]).then(([x])=>x.map(r=>parse(r,['payload_snapshot_json']))),
    db.execute('SELECT * FROM after_sales_events WHERE after_sales_case_id=? ORDER BY occurred_at,id',[caseId]).then(([x])=>x.map(r=>parse(r,['payload_json']))),
  ])
  return{case:parse(claim,['source_snapshot_json']),affected_items:lines,traceability:lines.map(line=>({case_line_id:line.id,trace_hash:line.trace_hash,source:line.source_snapshot_json,gaps:line.trace_gaps_json,fabricated_links:false})),evidence,investigation,resolutions,supplier_escalations:escalations,downstream_actions:handoffs,history:events,upstream_state_unchanged:{contract_status:claim.contract_status,contract_row_version:claim.contract_row_version,completion_state:claim.completion_state,completion_row_version:claim.completion_row_version,completion_snapshot_hash:claim.completion_snapshot_hash,claim_does_not_reopen_contract_or_completion:true}}
}

async function eligibleDeliveries(query={}){const clientId=toId(query.client_id),contractCaseId=toId(query.contract_case_id),params=[];const where=["dc.status='CONFIRMED'"];if(clientId){where.push('doo.client_id=?');params.push(clientId)}if(contractCaseId){where.push('doo.source_contract_case_id=?');params.push(contractCaseId)}const [rows]=await db.execute(`SELECT dcl.id dispatch_delivery_confirmation_line_id,dcl.delivered_quantity,dcl.uom,dc.id delivery_confirmation_id,dc.confirmation_number,dc.delivered_at,dc.evidence_reference,ds.id dispatch_shipment_id,ds.shipment_number,doo.client_id,cl.company_name,doo.source_contract_case_id contract_case_id,cc.contract_number,cc.aggregate_status contract_status,co.id contract_commitment_id,co.contract_line_id,doa.id dispatch_order_allocation_id,doa.catalog_position_id,
  (SELECT COUNT(*) FROM dispatch_package_contents dpc JOIN dispatch_shipment_packages dsp ON dsp.dispatch_package_id=dpc.dispatch_package_id WHERE dpc.dispatch_order_allocation_id=doa.id AND dsp.dispatch_shipment_id=ds.id) traceable_package_count
  FROM dispatch_delivery_confirmation_lines dcl JOIN dispatch_delivery_confirmations dc ON dc.id=dcl.dispatch_delivery_confirmation_id JOIN dispatch_shipments ds ON ds.id=dc.dispatch_shipment_id JOIN dispatch_order_allocations doa ON doa.id=dcl.dispatch_order_allocation_id JOIN dispatch_orders doo ON doo.id=doa.dispatch_order_id JOIN clients cl ON cl.id=doo.client_id JOIN contract_commitments co ON co.id=doa.contract_commitment_id JOIN contract_cases cc ON cc.id=co.contract_case_id WHERE ${where.join(' AND ')} ORDER BY dc.delivered_at DESC,dcl.id DESC LIMIT 500`,params);return{rows,data_gate:rows.length?null:'NO_CONFIRMED_DELIVERED_LINES',claim_creation_requires_confirmed_delivery:true,missing_trace_is_not_invented:true}
}

async function history(query={}){const params=[];const where=[];if(query.status){where.push('c.status=?');params.push(String(query.status).toUpperCase())}if(toId(query.client_id)){where.push('c.client_id=?');params.push(toId(query.client_id))}const [rows]=await db.execute(`SELECT c.id case_id,c.case_number,c.status,c.problem_classification,c.severity,c.opened_at,c.closed_at,cl.company_name,cc.contract_number,COUNT(e.id) event_count FROM after_sales_cases c JOIN clients cl ON cl.id=c.client_id JOIN contract_cases cc ON cc.id=c.contract_case_id LEFT JOIN after_sales_events e ON e.after_sales_case_id=c.id ${where.length?`WHERE ${where.join(' AND ')}`:''} GROUP BY c.id ORDER BY COALESCE(c.closed_at,c.updated_at) DESC,c.id DESC LIMIT 500`,params);return{rows,append_only_history:true,closed_searchable:true}}

async function supplierQuality(query={}){const supplierId=toId(query.supplier_id),params=[];const where=supplierId?'WHERE e.supplier_id=?':'';if(supplierId)params.push(supplierId);const [rows]=await db.execute(`SELECT e.supplier_id,s.company_name supplier_name,COUNT(DISTINCT e.after_sales_case_id) claim_count,COUNT(*) escalation_count,SUM(e.status IN ('OPEN','ACKNOWLEDGED')) active_escalation_count,MIN(e.opened_at) first_escalation_at,MAX(e.opened_at) latest_escalation_at FROM after_sales_supplier_escalations e JOIN part_suppliers s ON s.id=e.supplier_id ${where} GROUP BY e.supplier_id,s.company_name ORDER BY claim_count DESC`,params);return{rows,read_model_only:true,supplier_master_mutated:false,ranking_policy:false}}

module.exports={eligibleDeliveries,getCase,history,overview,supplierQuality}
